// 网站图标映射表 - 本地化版本
// 共 242 个网站图标
var iconMap = {
    "OpenClaw 官网": "icons/OpenClaw_官网.webp",
    "官方GitHub": "icons/官方GitHub.svg",
    "Kimi Claw": "icons/Kimi_Claw.webp",
    "MaxClaw": "icons/MaxClaw.webp",
    "飞书OpenClaw": "icons/飞书OpenClaw.webp",
    "ArkClaw": "icons/ArkClaw.webp",
    "扣子Coze": "icons/扣子Coze.webp",
    "DuClaw": "icons/DuClaw.webp",
    "Xiaomi MiMo Claw": "icons/Xiaomi_MiMo_Claw.webp",
    "StepClaw": "icons/StepClaw.webp",
    "AstronClaw": "icons/AstronClaw.webp",
    "Happycapy": "icons/Happycapy.webp",
    "Qclaw": "icons/Qclaw.webp",
    "DuMate": "icons/DuMate.webp",
    "LobsterAI 有道龙虾": "icons/LobsterAI_有道龙虾.webp",
    "WorkBuddy": "icons/WorkBuddy.webp",
    "AutoClaw": "icons/AutoClaw.webp",
    "悟空": "icons/悟空.webp",
    "360安全龙虾": "icons/360安全龙虾.webp",
    "QoderWork": "icons/QoderWork.webp",
    "阶跃桌面伙伴": "icons/阶跃桌面伙伴.webp",
    "JVS Claw": "icons/JVS_Claw.webp",
    "EasyClaw": "icons/EasyClaw.webp",
    "CoPaw": "icons/CoPaw.webp",
    "nexu": "icons/nexu.webp",
    "Manus": "icons/Manus.webp",
    "牛马 AI": "icons/牛马_AI.webp",
    "MuleRun": "icons/MuleRun.webp",
    "LobeHub": "icons/LobeHub.webp",
    "Tabbit 浏览器": "icons/Tabbit_浏览器.webp",
    "Linkfox Claw": "icons/Linkfox_Claw.webp",
    "PoorClaw穷虾": "icons/PoorClaw穷虾.webp",
    "HiClaw": "icons/HiClaw.webp",
    "KiloClaw": "icons/KiloClaw.webp",
    "NemoClaw": "icons/NemoClaw.webp",
    "Loomy": "icons/Loomy.webp",
    "Hermes Agent": "icons/Hermes_Agent.webp",
    "阿里云": "icons/阿里云.jpg",
    "腾讯云": "icons/腾讯云.jpg",
    "火山引擎": "icons/火山引擎.webp",
    "百度智能云": "icons/百度智能云.webp",
    "华为云": "icons/华为云.png",
    "京东云": "icons/京东云.webp",
    "国家超算互联网": "icons/国家超算互联网.webp",
    "天翼云": "icons/天翼云.webp",
    "官方文档": "icons/官方文档.svg",
    "OpenClaw 橙皮书": "icons/OpenClaw_橙皮书.webp",
    "万象 AI 实验室": "icons/万象_AI_实验室.webp",
    "WaytoAGI 之路": "icons/WaytoAGI_之路.webp",
    "非凡产研": "icons/非凡产研.webp",
    "OpenClaw 中文学习手册": "icons/OpenClaw_中文学习手册.webp",
    "OpenClaw 从入门到精通": "icons/OpenClaw_从入门到精通.webp",
    "Hello Claw 教程": "icons/Hello_Claw_教程.webp",
    "Awesome 教程": "icons/Awesome_教程.webp",
    "飞书官方修炼指南": "icons/飞书官方修炼指南.webp",
    "麻小玩虾指南": "icons/麻小玩虾指南.webp",
    "中文用例大全": "icons/中文用例大全.webp",
    "千问": "icons/千问.webp",
    "豆包": "icons/豆包.webp",
    "Kimi": "icons/Kimi.webp",
    "腾讯元宝": "icons/腾讯元宝.webp",
    "DeepSeek": "icons/DeepSeek.webp",
    "ChatGPT": "icons/ChatGPT.webp",
    "Gemini": "icons/Gemini.webp",
    "Grok": "icons/Grok.webp",
    "即梦AI": "icons/即梦AI.webp",
    "MiniMax Token Plan": "icons/MiniMax_Token_Plan.webp",
    "智谱 Coding Plan": "icons/智谱_Coding_Plan.webp",
    "腾讯云 Coding Plan": "icons/腾讯云_Coding_Plan.jpg",
    "阿里云Coding Plan": "icons/阿里云Coding_Plan.jpg",
    "火山引擎Coding Plan": "icons/火山引擎Coding_Plan.webp",
    "百度千帆Coding Plan": "icons/百度千帆Coding_Plan.png",
    "Step Plan": "icons/Step_Plan.webp",
    "腾讯云 Token Plan": "icons/腾讯云_Token_Plan.webp",
    "Xiaomi MiMo": "icons/Xiaomi_MiMo.webp",
    "火山方舟": "icons/火山方舟.webp",
    "百度千帆": "icons/百度千帆.png",
    "硅基流动": "icons/硅基流动.webp",
    "七牛云": "icons/七牛云.webp",
    "讯飞星火": "icons/讯飞星火.webp",
    "OpenRouter": "icons/OpenRouter.webp",
    "ZenMux": "icons/ZenMux.svg",
    "Model123": "icons/Model123.webp",
    "快手万擎": "icons/快手万擎.webp",
    "MiniMax": "icons/MiniMax.webp",
    "智谱GLM": "icons/智谱GLM.webp",
    "千问Qwen": "icons/千问Qwen.jpg",
    "豆包Doubao": "icons/豆包Doubao.webp",
    "Claude": "icons/Claude.webp",
    "GPT": "icons/GPT.webp",
    "Llama": "icons/Llama.svg",
    "Mistral": "icons/Mistral.webp",
    "MiMo": "icons/MiMo.webp",
    "腾讯混元": "icons/腾讯混元.webp",
    "百度文心": "icons/百度文心.webp",
    "阶跃星辰": "icons/阶跃星辰.webp",
    "PinchBench": "icons/PinchBench.webp",
    "Artificial Analysis": "icons/Artificial_Analysis.webp",
    "Arena.ai": "icons/Arena_ai.webp",
    "OpenRouter Rankings": "icons/OpenRouter_Rankings.webp",
    "XSCT Bench": "icons/XSCT_Bench.webp",
    "Vals AI": "icons/Vals_AI.svg",
    "ClawHub": "icons/ClawHub.webp",
    "SkillHub": "icons/SkillHub.webp",
    "Skills.sh": "icons/Skills_sh.webp",
    "SkillsMP": "icons/SkillsMP.webp",
    "虾评Skill": "icons/虾评Skill.webp",
    "SkillHub中国": "icons/SkillHub中国.webp",
    "Agent Skills Hub": "icons/Agent_Skills_Hub.webp",
    "OpenClaw Directory": "icons/OpenClaw_Directory.webp",
    "OpenClawDir": "icons/OpenClawDir.svg",
    "ClawSkills": "icons/ClawSkills.webp",
    "CryptoSkills": "icons/CryptoSkills.webp",
    "CocoLoop": "icons/CocoLoop.webp",
    "Xcrawl": "icons/Xcrawl.webp",
    "Moltbook": "icons/Moltbook.webp",
    "InStreet": "icons/InStreet.webp",
    "虾聊": "icons/虾聊.webp",
    "AgentMail": "icons/AgentMail.webp",
    "MailboxKit": "icons/MailboxKit.webp",
    "mails": "icons/mails.webp",
    "Souls.zip": "icons/Souls_zip.webp",
    "OpenClaw Startups": "icons/OpenClaw_Startups.webp",
    "曝光观察板": "icons/曝光观察板.webp",
    "Claw Bench 排行榜": "icons/Claw_Bench_排行榜.webp",
    "ClawPal": "icons/ClawPal.webp",
    "ClawWatcher": "icons/ClawWatcher.webp",
    "ClawManager": "icons/ClawManager.webp",
    "Control Center": "icons/Control_Center.svg",
    "水产市场": "icons/水产市场.webp",
    "EdgeOne ClawScan": "icons/EdgeOne_ClawScan.webp",
    "OpenClaw 使用案例": "icons/OpenClaw_使用案例.webp",
    "A2H Market": "icons/A2H_Market.webp",
    "Reddit板块": "icons/Reddit板块.webp",
    "Discord官方服务器": "icons/Discord官方服务器.webp",
    "Clawvard": "icons/Clawvard.webp",
    "Claw402": "icons/Claw402.webp",
    "SkillPay": "icons/SkillPay.webp",
    "FluxA": "icons/FluxA.webp",
    "AgentCard.ai": "icons/AgentCard_ai.webp",
    "AgentCard.sh": "icons/AgentCard_sh.webp",
    "Clawcard.sh": "icons/Clawcard_sh.webp",
    "Lobster.cash": "icons/Lobster_cash.webp",
    "Machines Cash": "icons/Machines_Cash.webp",
    "Gate Pay for AI": "icons/Gate_Pay_for_AI.webp",
    "Coinbase AgentKit": "icons/Coinbase_AgentKit.svg",
    "Tempo Wallet": "icons/Tempo_Wallet.webp",
    "ClawVault": "icons/ClawVault.webp",
    "ClawCredit": "icons/ClawCredit.webp",
    "PayAI": "icons/PayAI.webp",
    "Ampersend": "icons/Ampersend.webp",
    "OKX Agent Trade Kit": "icons/OKX_Agent_Trade_Kit.webp",
    "Binance Skills Hub": "icons/Binance_Skills_Hub.webp",
    "GetClaw": "icons/GetClaw.webp",
    "HTX AI Skills": "icons/HTX_AI_Skills.webp",
    "GateClaw": "icons/GateClaw.webp",
    "Bybit AI Hub": "icons/Bybit_AI_Hub.webp",
    "COIN CLAW": "icons/COIN_CLAW.webp",
    "AiCoin CoinOS": "icons/AiCoin_CoinOS.webp",
    "MoonPay Agents": "icons/MoonPay_Agents.webp",
    "Alchemy Ai Agent": "icons/Alchemy_Ai_Agent.webp",
    "Circle Skills": "icons/Circle_Skills.webp",
    "MetaMask Skill": "icons/MetaMask_Skill.webp",
    "PolyHub": "icons/PolyHub.webp",
    "KuCoin Skills Hub": "icons/KuCoin_Skills_Hub.webp",
    "Gate Skills Hub": "icons/Gate_Skills_Hub.webp",
    "Bitget Agent Hub": "icons/Bitget_Agent_Hub.webp",
    "Binance": "icons/Binance.webp",
    "OKX": "icons/OKX.webp",
    "Bitget": "icons/Bitget.webp",
    "Bybit": "icons/Bybit.webp",
    "Gate": "icons/Gate.webp",
    "KuCoin": "icons/KuCoin.webp",
    "Mexc": "icons/Mexc.webp",
    "HTX": "icons/HTX.webp",
    "Coinbase": "icons/Coinbase.webp",
    "Kraken": "icons/Kraken.webp",
    "Bitmart": "icons/Bitmart.webp",
    "Weex": "icons/Weex.webp",
    "XT.com": "icons/XT_com.webp",
    "Ju.com": "icons/Ju_com.webp",
    // MaaS平台新增
    "蓝耘元生代": "icons/蓝耘元生代.webp",
    "魔搭社区": "icons/魔搭社区.webp",
    "腾讯云TI平台": "icons/腾讯云TI平台.webp",
    // API聚合平台
    "PoloAPI": "icons/PoloAPI.webp",
    "weelinking": "icons/weelinking.webp",
    "n1n.ai": "icons/n1n_ai.webp",
    "147API": "icons/147API.webp",
    "Azure OpenAI": "icons/Azure_OpenAI.webp",
    // Agent开发平台
    "LangChain": "icons/LangChain.webp",
    "LangGraph": "icons/LangGraph.webp",
    "CrewAI": "icons/CrewAI.webp",
    "AutoGen": "icons/AutoGen.webp",
    "Dify": "icons/Dify.webp",
    "Kimi Agent Builder": "icons/Kimi_Agent_Builder.webp",
    "通义千问Agent Studio": "icons/通义千问Agent_Studio.webp",
    "腾讯混元Agent平台": "icons/腾讯混元Agent平台.webp",
    "MiniMax Agent Builder": "icons/MiniMax_Agent_Builder.webp",
    "智谱清言Agent Studio": "icons/智谱清言Agent_Studio.webp",
    "实在Agent": "icons/实在Agent.webp",
    "LangFlow": "icons/LangFlow.webp",
    "飞书Agent Builder": "icons/飞书Agent_Builder.webp",
    "豆包Agent Studio": "icons/豆包Agent_Studio.webp",
    "JeecgBoot": "icons/JeecgBoot.webp",
    // Agent沙箱
    "E2B": "icons/E2B.webp",
    "Modal Sandboxes": "icons/Modal_Sandboxes.webp",
    "Browserbase": "icons/Browserbase.webp",
    "Steel": "icons/Steel.webp",
    // AI编程工具
    "Claude Code": "icons/Claude_Code.webp",
    "Cursor": "icons/Cursor.webp",
    "GitHub Copilot": "icons/GitHub_Copilot.webp",
    "Codex CLI": "icons/Codex_CLI.webp",
    "Gemini CLI": "icons/Gemini_CLI.webp",
    // 国内AI编程工具
    "Trae": "icons/Trae.webp",
    "Qoder": "icons/Qoder.webp",
    "CodeBuddy": "icons/CodeBuddy.webp",
    "文心快码": "icons/文心快码.webp",
    "通义灵码": "icons/通义灵码.webp",
    "代码小浣熊": "icons/代码小浣熊.webp",
    "豆包MarsCode": "icons/豆包MarsCode.webp",
    "Kimi Code": "icons/Kimi_Code.webp",
    // 更多AI编程工具
    "Windsurf": "icons/Windsurf.webp",
    "Codeium": "icons/Codeium.webp",
    "Google AI Studio": "icons/Google_AI_Studio.webp",
    "Cline": "icons/Cline.webp",
    "CodeGeeX": "icons/CodeGeeX.webp",
    "JoyCode": "icons/JoyCode.webp",
    "Amazon Q Developer": "icons/Amazon_Q_Developer.webp",
    "Continue": "icons/Continue.webp",
    "Zed AI": "icons/Zed_AI.webp",
    "Aider": "icons/Aider.webp",
    "v0": "icons/v0.webp",
    // AI创作画布
    "Liblib": "icons/Liblib.webp",
    "Oii": "icons/Oii.webp",
    "即梦": "icons/即梦_画布.webp",
    "星流": "icons/星流.webp",
    // 语音大模型
    "VoxCPM2": "icons/VoxCPM2.png",
    "Qwen3-TTS": "icons/Qwen3-TTS.png",
    "Fish Speech": "icons/Fish_Speech.png",
    "ElevenLabs": "icons/ElevenLabs.png",
    "Voxtral": "icons/Voxtral.png",
    "OpenVoice": "icons/OpenVoice.png",
    "GLM-ASR-Nano": "icons/GLM_ASR_Nano.png",
    "SkyReels-V3": "icons/SkyReels_V3.png",
    "PaddleSpeech": "icons/PaddleSpeech.png",
    "MiniMax 语音": "icons/MiniMax_语音.ico",
    // AI音乐创作
    "Suno": "icons/Suno.png",
    "Udio": "icons/Udio.png",
    "Mureka": "icons/Mureka.png",
    "Soundful": "icons/Soundful.png",
    "Mubert": "icons/Mubert.svg",
    "AIVA": "icons/AIVA.png",
    "Boomy": "icons/Boomy.ico",
    "Stable Audio": "icons/Stable_Audio.png",
    "Google Lyria": "icons/Google_Lyria.svg",
    "Producer.AI": "icons/Producer_AI.png",
    "天工SkyMusic": "icons/天工SkyMusic.png",
    "网易天音 XStudio": "icons/网易天音_XStudio.png",
    "海绵音乐": "icons/海绵音乐.png",
    "谱乐": "icons/谱乐.png",
    "蘑兔AI": "icons/蘑兔AI.ico",
    "歌歌AI写歌": "icons/歌歌AI写歌.jpg",
    "Tunee": "icons/Tunee.png",
    "MiniMax 音乐": "icons/MiniMax_语音.ico",
    "Filmora AI Music": "icons/Filmora_AI_Music.png",
    "Soundraw": "icons/Soundraw.png",
    // 新增 2026-04-14
    "山海·知音": "icons/山海知音.png",
    "华为Agent Arts": "icons/华为Agent_Arts.png",
    "BetterYeah AI": "icons/BetterYeah_AI.png",
    "京东云JoyAgent": "icons/京东云JoyAgent.png",
    // 短剧Agent
    "小云雀AI": "icons/小云雀AI.webp",
    "ZenStudio": "icons/ZenStudio.webp",
    "Jellyfish": "icons/GitHub.webp",
    "剧火AI": "icons/剧火AI.webp",
    "可灵AI": "icons/可灵AI.webp",
    "盼趣AI": "icons/盼趣AI.webp",
    "火宝短剧": "icons/GitHub.webp",
    "灵果短剧AI": "icons/GitHub.webp",
    "百度AI短剧创作": "icons/百度AI短剧创作.webp",
    "Zopia": "icons/Zopia.webp",
    "万彩AI": "icons/万彩AI.webp",
    "万兴喵影": "icons/万兴喵影.webp",
    // 新增 2026-04-15
    "TabNine": "icons/TabNine.webp",
    "Gemma 4": "icons/Gemma4.webp",
    "瓴羊Quick Service": "icons/瓴羊QuickService.webp",
    "瓴羊Agent One": "icons/瓴羊AgentOne.webp",
    "音潮": "icons/音潮.webp",
    "Vemus未音": "icons/Vemus未音.png",
    // 新增 2026-04-16
    "Xiaomi MiMo-V2-TTS": "icons/Xiaomi_MiMo_V2_TTS.png",
    "佰分象AI": "icons/佰分象AI.jpg",
    "avavox": "icons/avavox.png",
    "Seeduplex": "icons/豆包.webp",
    // 新增 2026-04-17
    "云蝠智能": "icons/云蝠智能.png",
    "沃丰科技智呼机器人": "icons/沃丰科技.png",
    "铠盒智能": "icons/铠盒智能.png",
    // 新增 2026-04-18
    "CosyVoice3": "icons/GitHub.webp",
    "GPT-SoVITS": "icons/GitHub.webp",
    "IndexTTS-2": "icons/GitHub.webp",
    "Spark-TTS": "icons/GitHub.webp",
    "Whisper": "icons/GitHub.webp",
    "Qwen3-ASR": "icons/千问Qwen.jpg",
    "FunASR": "icons/GitHub.webp",
    "Qwen-Omni": "icons/千问Qwen.jpg",
    "GLM-4.1V-Thinking-Flash": "icons/智谱GLM.webp",
    "Sherpa-ONNX": "icons/GitHub.webp",
    "星链4SAPI": "icons/星链4SAPI.ico",
    "Lemonaid": null,
    "巨日禄": null,
    // 新增世界模型分类 2026-04-18
    "HappyOyster": "icons/HappyOyster.jpg",
    "WorldLabs Marble": null,
    "Meta V-JEPA 2": null,
    "Google Genie 2": null,
    "Runway GWM-1": "icons/Runway_GWM1.webp",
    "智元 Genie Envisioner": null,
    "蔚来世界模型": null,
    "特斯拉世界模型": null,
    // 新增 2026-04-20
    "Tabby": "icons/Tabby.avif",
    "VoiceFox": "icons/VoiceFox.png",
    "Hyperbrowser": "icons/Hyperbrowser.svg"
};

// 根据网站名称获取图标
function getIconByName(name) {
    // 处理名称中的特殊字符（如零宽空格）
    var cleanName = name.replace(/[\u200B\u200C\u200D\uFEFF]/g, '').trim();
    return iconMap[cleanName] || iconMap[name] || null;
}
