// 网站图标映射表 - 本地化版本
// 共 358 个网站图标
var iconMap = {
    "147API": "icons/147API.png",
    "360安全龙虾": "icons/360安全龙虾.png",
    "A2H Market": "icons/A2H_Market.png",
    "AI Rap Song Generator": "icons/AI_Rap_Song_Generator.png",
    "AIVA": "icons/AIVA.png",
    "Agent Skills Hub": "icons/Agent_Skills_Hub.png",
    "AgentCard.ai": "icons/AgentCardai.png",
    "AgentCard.sh": "icons/AgentCardsh.png",
    "AgentMail": "icons/AgentMail.png",
    "AiCoin CoinOS": "icons/AiCoin_CoinOS.png",
    "Aider": "icons/Aider.png",
    "Akiflow": "icons/Akiflow.png",
    "Alchemy Ai Agent": "icons/Alchemy_Ai_Agent.png",
    "Amazon Q Developer": "icons/Amazon_Q_Developer.png",
    "Ampersend": "icons/Ampersend.png",
    "Arena.ai": "icons/Arenaai.png",
    "ArkClaw": "icons/ArkClaw.png",
    "Artificial Analysis": "icons/Artificial_Analysis.png",
    "AstronClaw": "icons/AstronClaw.ico",
    "AutoClaw": "icons/AutoClaw.png",
    "AutoGen": "icons/AutoGen.webp",
    "Awesome 教程": "icons/Awesome_教程.webp",
    "Azure OpenAI": "icons/Azure_OpenAI.webp",
    "BetterYeah AI": "icons/BetterYeah_AI.png",
    "Binance": "icons/Binance.webp",
    "Binance Skills Hub": "icons/Binance_Skills_Hub.webp",
    "Bitget": "icons/Bitget.png",
    "Bitget Agent Hub": "icons/Bitget_Agent_Hub.png",
    "Bitmart": "icons/Bitmart.png",
    "Boomy": "icons/Boomy.ico",
    "Browserbase": "icons/Browserbase.png",
    "Bybit": "icons/Bybit.png",
    "Bybit AI Hub": "icons/Bybit_AI_Hub.png",
    "COIN CLAW": "icons/COIN_CLAW.png",
    "ChatGPT": "icons/ChatGPT.png",
    "Circle Skills": "icons/Circle_Skills.png",
    "Citeclops": "icons/Citeclops.png",
    "Claude": "icons/Claude.png",
    "Claude Code": "icons/Claude_Code.webp",
    "Claw Bench 排行榜": "icons/Claw_Bench_排行榜.png",
    "Claw402": "icons/Claw402.png",
    "ClawCredit": "icons/ClawCredit.png",
    "ClawHub": "icons/ClawHub.png",
    "ClawManager": "icons/ClawManager.png",
    "ClawPal": "icons/ClawPal.png",
    "ClawSkills": "icons/ClawSkills.webp",
    "ClawVault": "icons/ClawVault.png",
    "ClawWatcher": "icons/ClawWatcher.png",
    "Clawcard.sh": "icons/Clawcardsh.png",
    "Clawvard": "icons/Clawvard.png",
    "Cline": "icons/Cline.png",
    "CoPaw": "icons/CoPaw.svg",
    "CocoLoop": "icons/CocoLoop.png",
    "CodeBuddy": "icons/CodeBuddy.webp",
    "CodeGeeX": "icons/CodeGeeX.png",
    "Codeium": "icons/Codeium.webp",
    "Codex CLI": "icons/Codex_CLI.png",
    "Coinbase": "icons/Coinbase.png",
    "Coinbase AgentKit": "icons/Coinbase_AgentKit.svg",
    "Connected Papers": "icons/Connected_Papers.png",
    "Continue": "icons/Continue.png",
    "Control Center": "icons/Control_Center.svg",
    "CosyVoice3": "icons/CosyVoice3.png",
    "Course Hero": "icons/Course_Hero.png",
    "CrewAI": "icons/CrewAI.png",
    "CryptoSkills": "icons/CryptoSkills.webp",
    "Cursor": "icons/Cursor.png",
    "Daytona": "icons/Daytona.png",
    "DeepL": "icons/DeepL.png",
    "DeepSeek": "icons/DeepSeek.png",
    "Dify": "icons/Dify.png",
    "Discord官方服务器": "icons/Discord官方服务器.png",
    "Drawing Prompts Generator by Chatgpt": "icons/Drawing_Prompts_Generator_by_Chatgpt.png",
    "DuClaw": "icons/DuClaw.webp",
    "DuMate": "icons/DuMate.webp",
    "E2B": "icons/E2B.png",
    "EasyClaw": "icons/EasyClaw.png",
    "EdgeOne ClawScan": "icons/EdgeOne_ClawScan.webp",
    "ElevenLabs": "icons/ElevenLabs.png",
    "Filmora AI Music": "icons/Filmora_AI_Music.png",
    "Fish Speech": "icons/Fish_Speech.png",
    "FluxA": "icons/FluxA.png",
    "FunASR": "icons/FunASR.png",
    "GLM-4.1V-Thinking-Flash": "icons/GLM-41V-Thinking-Flash.png",
    "GLM-ASR-Nano": "icons/GLM-ASR-Nano.png",
    "GPT": "icons/GPT.png",
    "GPT Daddy": "icons/GPT_Daddy.png",
    "GPT-SoVITS": "icons/GPT-SoVITS.png",
    "GPTinf": "icons/GPTinf.png",
    "Gate": "icons/Gate.png",
    "Gate Pay for AI": "icons/Gate_Pay_for_AI.png",
    "Gate Skills Hub": "icons/Gate_Skills_Hub.png",
    "GateClaw": "icons/GateClaw.png",
    "Gemini": "icons/Gemini.png",
    "Gemini CLI": "icons/Gemini_CLI.png",
    "Gemma 4": "icons/Gemma_4.png",
    "Genius PT": "icons/Genius_PT.png",
    "GetClaw": "icons/GetClaw.png",
    "GitHub Copilot": "icons/GitHub_Copilot.png",
    "Goodnotes": "icons/Goodnotes.png",
    "Google AI Studio": "icons/Google_AI_Studio.png",
    "Google Genie 2": "icons/Google_Genie_2.png",
    "Google Lyria": "icons/Google_Lyria.svg",
    "Grok": "icons/Grok.png",
    "HTX": "icons/HTX.png",
    "HTX AI Skills": "icons/HTX_AI_Skills.png",
    "Happy Scribe": "icons/Happy_Scribe.png",
    "HappyOyster": "icons/HappyOyster.jpg",
    "Happycapy": "icons/Happycapy.png",
    "Hello Claw 教程": "icons/Hello_Claw_教程.png",
    "Hermes Agent": "icons/Hermes_Agent.png",
    "HiClaw": "icons/HiClaw.png",
    "HyperWrite AI": "icons/HyperWrite_AI.png",
    "Hyperbrowser": "icons/Hyperbrowser.svg",
    "InStreet": "icons/InStreet.png",
    "IndexTTS-2": "icons/IndexTTS-2.png",
    "JVS Claw": "icons/JVS_Claw.ico",
    "JeecgBoot": "icons/JeecgBoot.ico",
    "Jellyfish": "icons/Jellyfish.png",
    "JoyCode": "icons/JoyCode.ico",
    "Ju.com": "icons/Jucom.png",
    "Jukebox AI": "icons/Jukebox_AI.png",
    "KiloClaw": "icons/KiloClaw.png",
    "Kimi": "icons/Kimi.webp",
    "Kimi Agent Builder": "icons/Kimi_Agent_Builder.webp",
    "Kimi Claw": "icons/Kimi_Claw.webp",
    "Kimi Code": "icons/Kimi_Code.ico",
    "Kiro": "icons/Kiro.png",
    "Kraken": "icons/Kraken.png",
    "KuCoin": "icons/KuCoin.png",
    "KuCoin Skills Hub": "icons/KuCoin_Skills_Hub.png",
    "LangChain": "icons/LangChain.png",
    "LangFlow": "icons/LangFlow.webp",
    "LangGraph": "icons/LangGraph.png",
    "Lemonaid": "icons/Lemonaid.png",
    "Liblib": "icons/Liblib.webp",
    "Linkfox Claw": "icons/Linkfox_Claw.png",
    "Llama": "icons/Llama.svg",
    "LobeHub": "icons/LobeHub.png",
    "Lobster.cash": "icons/Lobstercash.png",
    "LobsterAI 有道龙虾": "icons/LobsterAI_有道龙虾.png",
    "Loomy": "icons/Loomy.png",
    "Machines Cash": "icons/Machines_Cash.png",
    "Magai": "icons/Magai.png",
    "MailboxKit": "icons/MailboxKit.png",
    "Manus": "icons/Manus.ico",
    "MaxClaw": "icons/MaxClaw.png",
    "Meta V-JEPA 2": "icons/Meta_V-JEPA_2.png",
    "MetaMask Skill": "icons/MetaMask_Skill.png",
    "Mexc": "icons/Mexc.webp",
    "MiMo": "icons/MiMo.png",
    "MiniMax": "icons/MiniMax.png",
    "MiniMax Agent Builder": "icons/MiniMax_Agent_Builder.webp",
    "MiniMax Token Plan": "icons/MiniMax_Token_Plan.png",
    "MiniMax 语音": "icons/MiniMax_语音.ico",
    "MiniMax 音乐": "icons/MiniMax_音乐.png",
    "Mistral": "icons/Mistral.png",
    "Modal Sandboxes": "icons/Modal_Sandboxes.ico",
    "Model123": "icons/Model123.webp",
    "Moltbook": "icons/Moltbook.png",
    "MoonPay Agents": "icons/MoonPay_Agents.png",
    "Mubert": "icons/Mubert.svg",
    "MuleRun": "icons/MuleRun.png",
    "Mureka": "icons/Mureka.png",
    "NemoClaw": "icons/NemoClaw.webp",
    "Notelier AI": "icons/Notelier_AI.png",
    "OKX": "icons/OKX.png",
    "OKX Agent Trade Kit": "icons/OKX_Agent_Trade_Kit.png",
    "Oii": "icons/Oii.png",
    "OpenClaw Directory": "icons/OpenClaw_Directory.png",
    "OpenClaw Startups": "icons/OpenClaw_Startups.png",
    "OpenClaw 中文学习手册": "icons/OpenClaw_中文学习手册.png",
    "OpenClaw 从入门到精通": "icons/OpenClaw_从入门到精通.png",
    "OpenClaw 使用案例": "icons/OpenClaw_使用案例.webp",
    "OpenClaw 官网": "icons/OpenClaw_官网.png",
    "OpenClaw 橙皮书": "icons/OpenClaw_橙皮书.png",
    "OpenClawDir": "icons/OpenClawDir.svg",
    "OpenRouter": "icons/OpenRouter.ico",
    "OpenRouter Rankings": "icons/OpenRouter_Rankings.png",
    "OpenVoice": "icons/OpenVoice.png",
    "PaddleSpeech": "icons/PaddleSpeech.png",
    "PayAI": "icons/PayAI.png",
    "Pic to Text": "icons/Pic_to_Text.png",
    "PinchBench": "icons/PinchBench.png",
    "PoloAPI": "icons/PoloAPI.png",
    "PolyHub": "icons/PolyHub.png",
    "PoorClaw穷虾": "icons/PoorClaw穷虾.png",
    "Producer.AI": "icons/ProducerAI.png",
    "Qclaw": "icons/Qclaw.png",
    "Qoder": "icons/Qoder.png",
    "QoderWork": "icons/QoderWork.png",
    "Qwen-Omni": "icons/Qwen-Omni.png",
    "Qwen3-ASR": "icons/Qwen3-ASR.png",
    "Qwen3-TTS": "icons/Qwen3-TTS.png",
    "ReadPaper Importer": "icons/ReadPaper_Importer.png",
    "Reddit板块": "icons/Reddit板块.png",
    "Runway GWM-1": "icons/Runway_GWM-1.png",
    "SERP Sonar": "icons/SERP_Sonar.png",
    "SIFA Reply": "icons/SIFA_Reply.png",
    "SafeSkill": "icons/SafeSkill.ico",
    "Sherpa-ONNX": "icons/Sherpa-ONNX.png",
    "SkillHub": "icons/SkillHub.png",
    "SkillHub中国": "icons/SkillHub中国.png",
    "SkillPay": "icons/SkillPay.webp",
    "Skills.sh": "icons/Skillssh.png",
    "SkillsMP": "icons/SkillsMP.png",
    "SkyReels-V3": "icons/SkyReels-V3.png",
    "SlidesPilot": "icons/SlidesPilot.png",
    "Souls.zip": "icons/Soulszip.png",
    "Soundful": "icons/Soundful.png",
    "Soundraw": "icons/Soundraw.png",
    "Spark-TTS": "icons/Spark-TTS.png",
    "Spinrewriter": "icons/Spinrewriter.png",
    "Stable Audio": "icons/Stable_Audio.png",
    "Steel": "icons/Steel.png",
    "Step Plan": "icons/Step_Plan.png",
    "StepClaw": "icons/StepClaw.png",
    "Story321 Music AI": "icons/Story321_Music_AI.png",
    "Suno": "icons/Suno.png",
    "Suno AI Music Generator Free Online": "icons/Suno_AI_Music_Generator_Free_Online.png",
    "SuperApply": "icons/SuperApply.png",
    "Supermaven": "icons/Supermaven.png",
    "TabNine": "icons/TabNine.png",
    "Tabbit 浏览器": "icons/Tabbit_浏览器.png",
    "Tabby": "icons/Tabby.png",
    "Tempo Wallet": "icons/Tempo_Wallet.png",
    "Trae": "icons/Trae.png",
    "Tunee": "icons/Tunee.png",
    "Udio": "icons/Udio.png",
    "Vals AI": "icons/Vals_AI.svg",
    "Vemus未音": "icons/Vemus未音.png",
    "VoiceFox": "icons/VoiceFox.png",
    "VoxCPM2": "icons/VoxCPM2.png",
    "Voxtral": "icons/Voxtral.png",
    "WPS智能写作": "icons/WPS智能写作.png",
    "WaytoAGI 之路": "icons/WaytoAGI_之路.png",
    "Weex": "icons/Weex.png",
    "Whisper": "icons/Whisper.png",
    "Windsurf": "icons/Windsurf.ico",
    "WorkBuddy": "icons/WorkBuddy.svg",
    "WorldLabs Marble": "icons/WorldLabs_Marble.png",
    "XSCT Bench": "icons/XSCT_Bench.webp",
    "XT.com": "icons/XTcom.png",
    "Xcrawl": "icons/Xcrawl.png",
    "Xiaomi MiMo": "icons/Xiaomi_MiMo.png",
    "Xiaomi MiMo Claw": "icons/Xiaomi_MiMo_Claw.png",
    "Xiaomi MiMo-V2-TTS": "icons/Xiaomi_MiMo-V2-TTS.png",
    "Yignite助手": "icons/Yignite助手.png",
    "Yoomナレッジ": "icons/Yoomナレッジ.png",
    "Zed AI": "icons/Zed_AI.png",
    "ZenMux": "icons/ZenMux.svg",
    "ZenStudio": "icons/ZenStudio.png",
    "Zopia": "icons/Zopia.png",
    "avavox": "icons/avavox.png",
    "beeazt": "icons/beeazt.png",
    "formNinja": "icons/formNinja.png",
    "hahaOCR": "icons/hahaOCR.png",
    "mails": "icons/mails.png",
    "myEssai": "icons/myEssai.png",
    "n1n.ai": "icons/n1nai.png",
    "nexu": "icons/nexu.png",
    "theSkills.ai": "icons/theSkillsai.png",
    "v0": "icons/v0.png",
    "weelinking": "icons/weelinking.png",
    "七牛云": "icons/七牛云.ico",
    "万兴喵影": "icons/万兴喵影.png",
    "万彩AI": "icons/万彩AI.png",
    "万象 AI 实验室": "icons/万象_AI_实验室.png",
    "中文用例大全": "icons/中文用例大全.png",
    "云蝠智能": "icons/云蝠智能.png",
    "京东云": "icons/京东云.png",
    "京东云JoyAgent": "icons/京东云JoyAgent.png",
    "代码小浣熊": "icons/代码小浣熊.png",
    "佰分象AI": "icons/佰分象AI.ico",
    "元景大模型MaaS平台": "icons/元景大模型MaaS平台.png",
    "剧火AI": "icons/剧火AI.png",
    "千问": "icons/千问.png",
    "千问Qwen": "icons/千问Qwen.png",
    "华为Agent Arts": "icons/华为Agent_Arts.png",
    "华为云": "icons/华为云.png",
    "即梦": "icons/即梦.png",
    "即梦AI": "icons/即梦AI.ico",
    "可灵AI": "icons/可灵AI.png",
    "国家超算互联网": "icons/国家超算互联网.png",
    "天工SkyMusic": "icons/天工SkyMusic.png",
    "天翼云": "icons/天翼云.ico",
    "官方GitHub": "icons/官方GitHub.png",
    "官方文档": "icons/官方文档.png",
    "实在Agent": "icons/实在Agent.png",
    "小云雀AI": "icons/小云雀AI.png",
    "山海·知音": "icons/山海知音.png",
    "巨日禄": "icons/巨日禄.png",
    "快手万擎": "icons/快手万擎.png",
    "悟空": "icons/悟空.webp",
    "扣子Coze": "icons/扣子Coze.webp",
    "文心快码": "icons/文心快码.png",
    "星流": "icons/星流.png",
    "星链4SAPI": "icons/星链4SAPI.png",
    "智元 Genie Envisioner": "icons/智元_Genie_Envisioner.png",
    "智谱 Coding Plan": "icons/智谱_Coding_Plan.png",
    "智谱GLM": "icons/智谱GLM.png",
    "智谱清言Agent Studio": "icons/智谱清言Agent_Studio.webp",
    "曝光观察板": "icons/曝光观察板.png",
    "歌歌AI写歌": "icons/歌歌AI写歌.jpg",
    "水产市场": "icons/水产市场.webp",
    "沃丰科技智呼机器人": "icons/沃丰科技智呼机器人.png",
    "海绵音乐": "icons/海绵音乐.png",
    "火宝短剧": "icons/火宝短剧.png",
    "火山引擎": "icons/火山引擎.png",
    "火山引擎Coding Plan": "icons/火山引擎Coding_Plan.png",
    "火山方舟": "icons/火山方舟.png",
    "灵果短剧AI": "icons/灵果短剧AI.png",
    "牛马 AI": "icons/牛马_AI.ico",
    "特斯拉世界模型": "icons/特斯拉世界模型.png",
    "瓴羊Agent One": "icons/瓴羊Agent_One.png",
    "瓴羊Quick Service": "icons/瓴羊Quick_Service.png",
    "百度AI短剧创作": "icons/百度AI短剧创作.png",
    "百度千帆": "icons/百度千帆.png",
    "百度千帆Coding Plan": "icons/百度千帆Coding_Plan.png",
    "百度文心": "icons/百度文心.png",
    "百度智能云": "icons/百度智能云.ico",
    "盼趣AI": "icons/盼趣AI.png",
    "硅基流动": "icons/硅基流动.png",
    "网易天音 XStudio": "icons/网易天音_XStudio.png",
    "腾讯云": "icons/腾讯云.jpg",
    "腾讯云 Coding Plan": "icons/腾讯云_Coding_Plan.jpg",
    "腾讯云 Token Plan": "icons/腾讯云_Token_Plan.webp",
    "腾讯云TI平台": "icons/腾讯云TI平台.ico",
    "腾讯元宝": "icons/腾讯元宝.png",
    "腾讯混元": "icons/腾讯混元.png",
    "腾讯混元Agent平台": "icons/腾讯混元Agent平台.ico",
    "蓝耘元生代": "icons/蓝耘元生代.png",
    "蔚来世界模型": "icons/蔚来世界模型.png",
    "蘑兔AI": "icons/蘑兔AI.ico",
    "虾聊": "icons/虾聊.png",
    "虾评Skill": "icons/虾评Skill.png",
    "蚂蚁数科 Agentar": "icons/蚂蚁数科_Agentar.ico",
    "讯飞星火": "icons/讯飞星火.webp",
    "谱乐": "icons/谱乐.png",
    "豆包": "icons/豆包.png",
    "豆包Agent Studio": "icons/豆包Agent_Studio.png",
    "豆包Doubao": "icons/豆包Doubao.webp",
    "豆包MarsCode": "icons/豆包MarsCode.png",
    "通义千问Agent Studio": "icons/通义千问Agent_Studio.webp",
    "通义灵码": "icons/通义灵码.png",
    "铠盒智能": "icons/铠盒智能.png",
    "阶跃星辰": "icons/阶跃星辰.png",
    "阶跃桌面伙伴": "icons/阶跃桌面伙伴.png",
    "阿里云": "icons/阿里云.png",
    "阿里云 AgentBay": "icons/阿里云_AgentBay.png",
    "阿里云Coding Plan": "icons/阿里云Coding_Plan.png",
    "非凡产研": "icons/非凡产研.png",
    "音潮": "icons/音潮.png",
    "飞书Agent Builder": "icons/飞书Agent_Builder.png",
    "飞书OpenClaw": "icons/飞书OpenClaw.png",
    "飞书官方修炼指南": "icons/飞书官方修炼指南.png",
    "魔搭社区": "icons/魔搭社区.ico",
    "麻小玩虾指南": "icons/麻小玩虾指南.png",
};

// 根据网站名称获取图标
function getIconByName(name) {
    // 处理名称中的特殊字符（如零宽空格）
    var cleanName = name.replace(/[\u200B\u200C\u200D\uFEFF]/g, "").trim();
    return iconMap[cleanName] || iconMap[name] || null;
}
