// 网站图标映射表 - 本地化版本
// 共 2251 个网站图标
var iconMap = {
    "123Colorize": "icons/123Colorize.png",
    "135 AI排版": "icons/135_AI排版.png",
    "147API": "icons/147API.png",
    "15minuteplan.ai": "icons/15minuteplanai.png",
    "360安全龙虾": "icons/360安全龙虾.png",
    "360智绘": "icons/360智绘.png",
    "360智脑": "icons/360智脑.png",
    "42Signals": "icons/42Signals.png",
    "5118 SEO优化精灵": "icons/5118_SEO优化精灵.png",
    "66AI论文": "icons/66AI论文.png",
    "66论文": "icons/66论文.png",
    "88stacks": "icons/88stacks.png",
    "@imagetotext.me": "icons/imagetotextme.png",
    "A2H Market": "icons/A2H_Market.png",
    "AGI-Eval": "icons/AGI-Eval.png",
    "AI Answers to Your Pet Question": "icons/AI_Answers_to_Your_Pet_Question.png",
    "AI Blood Test Analysis": "icons/AI_Blood_Test_Analysis.png",
    "AI Bot Calorease.in": "icons/AI_Bot_Caloreasein.png",
    "AI Brain Bank – Chat with ALL Your Data": "icons/AI_Brain_Bank_Chat_with_ALL_Your_Data.png",
    "AI Bypasser": "icons/AI_Bypasser.png",
    "AI Chat PowerBrain": "icons/AI_Chat_PowerBrain.png",
    "AI Coach Amotions": "icons/AI_Coach_Amotions.png",
    "AI Code Reviewer": "icons/AI_Code_Reviewer.png",
    "AI Commects & Replies for Facebook™": "icons/AI_Commects_Replies_for_Facebook.png",
    "AI Content Detector": "icons/AI_Content_Detector.png",
    "AI Content Detector – Copyleaks": "icons/AI_Content_Detector_Copyleaks.png",
    "AI Cover Letter Generator by Kickresume": "icons/AI_Cover_Letter_Generator_by_Kickresume.png",
    "AI Detector for ChatGPT & more – Winston AI": "icons/AI_Detector_for_ChatGPT_more_Winston_AI.png",
    "AI Dezigner": "icons/AI_Dezigner.png",
    "AI Email Generator": "icons/AI_Email_Generator.png",
    "AI Emoji Generator": "icons/AI_Emoji_Generator.png",
    "AI Front-End Code Generator": "icons/AI_Front-End_Code_Generator.png",
    "AI Garage Sale": "icons/AI_Garage_Sale.png",
    "AI Hugging": "icons/AI_Hugging.png",
    "AI Illustwitter": "icons/AI_Illustwitter.png",
    "AI Image Enhancer&Upscaler": "icons/AI_Image_EnhancerUpscaler.png",
    "AI Image Generation": "icons/AI_Image_Generation.png",
    "AI Music Creator: Text to Song": "icons/AI_Music_Creator_Text_to_Song.png",
    "AI Music Sampler": "icons/AI_Music_Sampler.png",
    "AI Old Photo Restoration Online – ImgKit": "icons/AI_Old_Photo_Restoration_Online_ImgKit.png",
    "AI Pro Trading Signal": "icons/AI_Pro_Trading_Signal.png",
    "AI Product Photography": "icons/AI_Product_Photography.png",
    "AI Product Tools": "icons/AI_Product_Tools.png",
    "AI Prompt Finder": "icons/AI_Prompt_Finder.png",
    "AI Prompt Generator": "icons/AI_Prompt_Generator.png",
    "AI Prompt Library by God of Prompt": "icons/AI_Prompt_Library_by_God_of_Prompt.png",
    "AI Quiz Solver – Solve Your Quiz Easily": "icons/AI_Quiz_Solver_Solve_Your_Quiz_Easily.png",
    "AI Rap Song Generator": "icons/AI_Rap_Song_Generator.png",
    "AI SEO Optimizer for Claude": "icons/AI_SEO_Optimizer_for_Claude.png",
    "AI Short": "icons/AI_Short.png",
    "AI Social Post Generator": "icons/AI_Social_Post_Generator.png",
    "AI Song": "icons/AI_Song.png",
    "AI Song Lyrics Generator -Craft Unique Lyrics": "icons/AI_Song_Lyrics_Generator_-Craft_Unique_Lyrics.png",
    "AI Song Name Generator": "icons/AI_Song_Name_Generator.png",
    "AI Store Manager": "icons/AI_Store_Manager.png",
    "AI Story Generator": "icons/AI_Story_Generator.png",
    "AI Surge Cloud": "icons/AI_Surge_Cloud.png",
    "AI Therapy Hub – Your Counselor": "icons/AI_Therapy_Hub_Your_Counselor.png",
    "AI Tools Bay": "icons/AI_Tools_Bay.png",
    "AI Tools For Your Everyday Use": "icons/AI_Tools_For_Your_Everyday_Use.png",
    "AI Top100": "icons/AI_Top100.png",
    "AI Travel Selfies": "icons/AI_Travel_Selfies.png",
    "AI Trend Report": "icons/AI_Trend_Report.png",
    "AI UNDETECT": "icons/AI_UNDETECT.png",
    "AI URL to Video": "icons/AI_URL_to_Video.png",
    "AI VYX": "icons/AI_VYX.png",
    "AI illustraton generator": "icons/AI_illustraton_generator.png",
    "AI-Flow": "icons/AI-Flow.png",
    "AI-Powered Idea Validation": "icons/AI-Powered_Idea_Validation.png",
    "AI-Suite: Azen": "icons/AI-Suite_Azen.png",
    "AI-powered Digital Marketing": "icons/AI-powered_Digital_Marketing.png",
    "AI2image": "icons/AI2image.png",
    "AICVPro": "icons/AICVPro.png",
    "AIDesign": "icons/AIDesign.png",
    "AIDocumentMaker": "icons/AIDocumentMaker.png",
    "AIMailman": "icons/AIMailman.png",
    "AIO": "icons/AIO.png",
    "AIPRM": "icons/AIPRM.png",
    "AIPaperPass": "icons/AIPaperPass.png",
    "AIRadio.Host": "icons/AIRadioHost.png",
    "AISEO AI Content Detector": "icons/AISEO_AI_Content_Detector.png",
    "AIVA": "icons/AIVA.png",
    "AIvocado": "icons/AIvocado.png",
    "AI写信插件-外贸人必用": "icons/AI写信插件-外贸人必用.png",
    "AI大学堂": "icons/AI大学堂.png",
    "AI新媒体文章": "icons/AI新媒体文章.png",
    "AI检测工具导航平台": "icons/AI检测工具导航平台.png",
    "AI论文君": "icons/AI论文君.png",
    "AI速配（AiSoup）": "icons/AI速配AiSoup.png",
    "ALWIN": "icons/ALWIN.png",
    "AMZX": "icons/AMZX.png",
    "APEX AI": "icons/APEX_AI.png",
    "ARTROBOT": "icons/ARTROBOT.png",
    "ASO Assistant with ChatGPT": "icons/ASO_Assistant_with_ChatGPT.png",
    "ATS Crusher": "icons/ATS_Crusher.png",
    "AVCLabs": "icons/AVCLabs.png",
    "Aardvark": "icons/Aardvark.png",
    "Accoladeum": "icons/Accoladeum.png",
    "Ad Mocker": "icons/Ad_Mocker.png",
    "AdCopy.ai": "icons/AdCopyai.png",
    "Adadot for Developers": "icons/Adadot_for_Developers.png",
    "Adobe Image Background Remover": "icons/Adobe_Image_Background_Remover.png",
    "Adobe Podcast": "icons/Adobe_Podcast.png",
    "AdsDog": "icons/AdsDog.png",
    "Agent Skills Hub": "icons/Agent_Skills_Hub.png",
    "AgentCard.ai": "icons/AgentCardai.png",
    "AgentCard.sh": "icons/AgentCardsh.png",
    "AgentGPT": "icons/AgentGPT.png",
    "AgentMail": "icons/AgentMail.png",
    "Ager.fun": "icons/Agerfun.png",
    "Ai Background Removal and Generation": "icons/Ai_Background_Removal_and_Generation.png",
    "Ai Socialbot": "icons/Ai_Socialbot.png",
    "Ai Sofiya": "icons/Ai_Sofiya.png",
    "AiCanvas": "icons/AiCanvas.png",
    "AiCoin CoinOS": "icons/AiCoin_CoinOS.png",
    "Aidejuridique.ai": "icons/Aidejuridiqueai.png",
    "Aider": "icons/Aider.png",
    "Ainsys": "icons/Ainsys.png",
    "Aiomi: AI Assistant": "icons/Aiomi_AI_Assistant.png",
    "AirOps": "icons/AirOps.png",
    "Aire": "icons/Aire.png",
    "Airpost": "icons/Airpost.png",
    "Aissistant": "icons/Aissistant.png",
    "Aiter.io": "icons/Aiterio.png",
    "AixStock": "icons/AixStock.png",
    "Akiflow": "icons/Akiflow.png",
    "Alchemy Ai Agent": "icons/Alchemy_Ai_Agent.png",
    "AliExpress Image Search": "icons/AliExpress_Image_Search.png",
    "Alice AI extension": "icons/Alice_AI_extension.png",
    "Align": "icons/Align.png",
    "AllWriting": "icons/AllWriting.png",
    "Allotropy Studio": "icons/Allotropy_Studio.png",
    "Alpaca": "icons/Alpaca.png",
    "Alpha Sender": "icons/Alpha_Sender.png",
    "Alphabird AI": "icons/Alphabird_AI.png",
    "Alta": "icons/Alta.png",
    "Altos AI – Autonomous Advertising": "icons/Altos_AI_Autonomous_Advertising.png",
    "Alvatix": "icons/Alvatix.png",
    "Amazon Q Developer": "icons/Amazon_Q_Developer.png",
    "AmazonGPT Pros & Cons Analyzer": "icons/AmazonGPT_Pros_Cons_Analyzer.png",
    "Ampersend": "icons/Ampersend.png",
    "Amplemarket": "icons/Amplemarket.png",
    "Analytics Model": "icons/Analytics_Model.png",
    "Analyzr": "icons/Analyzr.png",
    "AnyTracker": "icons/AnyTracker.png",
    "Anylang.ai": "icons/Anylangai.png",
    "Apache MXNet": "icons/Apache_MXNet.png",
    "Apollo Co-Pilot Beta": "icons/Apollo_Co-Pilot_Beta.png",
    "ApolloAI": "icons/ApolloAI.png",
    "Apowersoft": "icons/Apowersoft.png",
    "AppFlowy: open-source Notion alternative": "icons/AppFlowy_open-source_Notion_alternative.png",
    "Appicons AI": "icons/Appicons_AI.png",
    "April AI": "icons/April_AI.png",
    "Arcads": "icons/Arcads.png",
    "ArchitectAI": "icons/ArchitectAI.png",
    "Archittect": "icons/Archittect.png",
    "Archsense": "icons/Archsense.png",
    "Arena.ai": "icons/Arenaai.png",
    "Ares creative": "icons/Ares_creative.png",
    "Argil": "icons/Argil.png",
    "ArkClaw": "icons/ArkClaw.png",
    "ArtSpace.ai": "icons/ArtSpaceai.png",
    "Article Lab AI": "icons/Article_Lab_AI.png",
    "ArticleAI.io": "icons/ArticleAIio.png",
    "Artificial Analysis": "icons/Artificial_Analysis.png",
    "Ask AI – AI Powered Chat Bot Assistant": "icons/Ask_AI_AI_Powered_Chat_Bot_Assistant.png",
    "AskCodi": "icons/AskCodi.png",
    "AskToSell": "icons/AskToSell.png",
    "AssemblyAI": "icons/AssemblyAI.png",
    "Astria": "icons/Astria.png",
    "AstronClaw": "icons/AstronClaw.ico",
    "Athenic AI": "icons/Athenic_AI.png",
    "Attentionkart": "icons/Attentionkart.png",
    "AudiOverFlow": "icons/AudiOverFlow.png",
    "Audio Muse": "icons/Audio_Muse.png",
    "Audiobox": "icons/Audiobox.png",
    "Audo Studio": "icons/Audo_Studio.png",
    "Augment": "icons/Augment.png",
    "Augnito": "icons/Augnito.png",
    "Aurk": "icons/Aurk.png",
    "Auto-GPT": "icons/Auto-GPT.png",
    "AutoBiz": "icons/AutoBiz.png",
    "AutoClaw": "icons/AutoClaw.png",
    "AutoGen": "icons/AutoGen.webp",
    "AutoKT": "icons/AutoKT.png",
    "AutoPitch.ai": "icons/AutoPitchai.png",
    "Autonoma": "icons/Autonoma.png",
    "Autopilot Shorts": "icons/Autopilot_Shorts.png",
    "Avais AI": "icons/Avais_AI.png",
    "Avath": "icons/Avath.png",
    "Avey": "icons/Avey.png",
    "Avian": "icons/Avian.png",
    "Avtaar.ai": "icons/Avtaarai.png",
    "Avumi": "icons/Avumi.png",
    "Awesome ChatGPT Prompts": "icons/Awesome_ChatGPT_Prompts.png",
    "Awesome Prompts": "icons/Awesome_Prompts.png",
    "Awesome 教程": "icons/Awesome_教程.webp",
    "Azna AI": "icons/Azna_AI.png",
    "Azomas – Quick Access To ChatGPT": "icons/Azomas_Quick_Access_To_ChatGPT.png",
    "Azure OpenAI": "icons/Azure_OpenAI.webp",
    "BGremover": "icons/BGremover.png",
    "BLACKBOX AI": "icons/BLACKBOX_AI.png",
    "BLOOM": "icons/BLOOM.png",
    "Babylon Voice – AI Voice GPT and VoiceID": "icons/Babylon_Voice_AI_Voice_GPT_and_VoiceID.png",
    "Background Eraser": "icons/Background_Eraser.png",
    "Bad Bot Design": "icons/Bad_Bot_Design.png",
    "Bannerbear": "icons/Bannerbear.png",
    "BarGPT AI-Powered Bartender": "icons/BarGPT_AI-Powered_Bartender.png",
    "Barrs AI": "icons/Barrs_AI.png",
    "BeC AI": "icons/BeC_AI.png",
    "Beaseness": "icons/Beaseness.png",
    "Beatoven.ai": "icons/Beatovenai.png",
    "Beb.ai": "icons/Bebai.png",
    "Becc.ai": "icons/Beccai.png",
    "Bee Unicorn": "icons/Bee_Unicorn.png",
    "BetterYeah AI": "icons/BetterYeah_AI.png",
    "Bg Eraser": "icons/Bg_Eraser.png",
    "BgRem": "icons/BgRem.png",
    "BgSub": "icons/BgSub.png",
    "BigJPG": "icons/BigJPG.png",
    "BigModel": "icons/BigModel.png",
    "Binance": "icons/Binance.webp",
    "Binance Skills Hub": "icons/Binance_Skills_Hub.webp",
    "Bing Image Creator": "icons/Bing_Image_Creator.png",
    "Bitget": "icons/Bitget.png",
    "Bitget Agent Hub": "icons/Bitget_Agent_Hub.png",
    "Bitmart": "icons/Bitmart.png",
    "Bito AI: Bring ChatGPT to your IDE for devs": "icons/Bito_AI_Bring_ChatGPT_to_your_IDE_for_devs.png",
    "BizMagnets": "icons/BizMagnets.png",
    "Bizway": "icons/Bizway.png",
    "Blackray": "icons/Blackray.png",
    "Blainy": "icons/Blainy.png",
    "BlogFAST": "icons/BlogFAST.png",
    "BlogToVideoAI": "icons/BlogToVideoAI.png",
    "BlozumAI": "icons/BlozumAI.png",
    "Boggl AI": "icons/Boggl_AI.png",
    "Boloo Buddy": "icons/Boloo_Buddy.png",
    "Bongocat": "icons/Bongocat.png",
    "Boomy": "icons/Boomy.ico",
    "BoostioAI": "icons/BoostioAI.png",
    "Boostramp": "icons/Boostramp.png",
    "Booth.ai": "icons/Boothai.png",
    "BotDistrikt": "icons/BotDistrikt.png",
    "Botello": "icons/Botello.png",
    "Boxsy": "icons/Boxsy.png",
    "Boxy": "icons/Boxy.png",
    "Brain Behind": "icons/Brain_Behind.png",
    "Brandmark": "icons/Brandmark.png",
    "Brev.ai": "icons/Brevai.png",
    "BrideLook AI: Hairstyle Designer": "icons/BrideLook_AI_Hairstyle_Designer.png",
    "Brightroom AI": "icons/Brightroom_AI.png",
    "Briskwrite": "icons/Briskwrite.png",
    "Browserbase": "icons/Browserbase.png",
    "Browserbear": "icons/Browserbear.png",
    "BudgetSEO": "icons/BudgetSEO.png",
    "BuildYourBrand-AI": "icons/BuildYourBrand-AI.png",
    "BuyLensAI": "icons/BuyLensAI.png",
    "Bybit": "icons/Bybit.png",
    "Bybit AI Hub": "icons/Bybit_AI_Hub.png",
    "Byrdhouse": "icons/Byrdhouse.png",
    "C-Eval": "icons/C-Eval.png",
    "CMMLU": "icons/CMMLU.png",
    "COIN CLAW": "icons/COIN_CLAW.png",
    "CONTADU": "icons/CONTADU.png",
    "CRUDERRA": "icons/CRUDERRA.png",
    "CV Maker AI": "icons/CV_Maker_AI.png",
    "CYTK": "icons/CYTK.png",
    "Caffe": "icons/Caffe.png",
    "Cala": "icons/Cala.png",
    "Cambrian": "icons/Cambrian.png",
    "Camocopy": "icons/Camocopy.png",
    "CanDoo – Find better information faster": "icons/CanDoo_Find_better_information_faster.png",
    "CandorIQ": "icons/CandorIQ.png",
    "Cantian AI": "icons/Cantian_AI.png",
    "Cantrip": "icons/Cantrip.png",
    "Cappella": "icons/Cappella.png",
    "Capsule": "icons/Capsule.png",
    "CaptainGPT": "icons/CaptainGPT.png",
    "CaptionGen.io": "icons/CaptionGenio.png",
    "Captions": "icons/Captions.png",
    "CarLingo": "icons/CarLingo.png",
    "Cardamore AI": "icons/Cardamore_AI.png",
    "CareerComposeAI: Cover Letter Powered by GPT": "icons/CareerComposeAI_Cover_Letter_Powered_by_GPT.png",
    "Cart Buddy GPT": "icons/Cart_Buddy_GPT.png",
    "Case Study Writer": "icons/Case_Study_Writer.png",
    "CaseGenius": "icons/CaseGenius.png",
    "Cat’s Eye": "icons/Cats_Eye.png",
    "Ceeya AI": "icons/Ceeya_AI.png",
    "Celerforge": "icons/Celerforge.png",
    "Censored AI": "icons/Censored_AI.png",
    "Cerelyze": "icons/Cerelyze.png",
    "ChainGPT": "icons/ChainGPT.png",
    "Character.AI": "icons/CharacterAI.png",
    "Charley": "icons/Charley.png",
    "Chat BI": "icons/Chat_BI.png",
    "Chat2CSV": "icons/Chat2CSV.png",
    "ChatArt": "icons/ChatArt.png",
    "ChatDev": "icons/ChatDev.png",
    "ChatGPT": "icons/ChatGPT.png",
    "ChatGPT Mail": "icons/ChatGPT_Mail.png",
    "ChatGPT Prompt Genius": "icons/ChatGPT_Prompt_Genius.png",
    "ChatGPT Prompts": "icons/ChatGPT_Prompts.png",
    "ChatGPT Shortcut": "icons/ChatGPT_Shortcut.png",
    "ChatGPT Vision for ALL": "icons/ChatGPT_Vision_for_ALL.png",
    "ChatGPT for Shop": "icons/ChatGPT_for_Shop.png",
    "ChatGPT2Help Chrome Extension": "icons/ChatGPT2Help_Chrome_Extension.png",
    "ChatGenius: Smart AI Assistant": "icons/ChatGenius_Smart_AI_Assistant.png",
    "ChatOverlay": "icons/ChatOverlay.png",
    "ChatVerse": "icons/ChatVerse.png",
    "Chatbot Arena": "icons/Chatbot_Arena.png",
    "CheatScrub GPT Detector": "icons/CheatScrub_GPT_Detector.png",
    "Cheddar Flow": "icons/Cheddar_Flow.png",
    "ChitChop": "icons/ChitChop.png",
    "Chromatic Lens": "icons/Chromatic_Lens.png",
    "Cici": "icons/Cici.png",
    "Circle Skills": "icons/Circle_Skills.png",
    "Circulife": "icons/Circulife.png",
    "Citeclops": "icons/Citeclops.png",
    "Civitai": "icons/Civitai.png",
    "ClassroomIO": "icons/ClassroomIO.png",
    "Claude": "icons/Claude.png",
    "Claude Code": "icons/Claude_Code.webp",
    "ClaudeSave": "icons/ClaudeSave.png",
    "Claw Bench 排行榜": "icons/Claw_Bench_排行榜.png",
    "Claw402": "icons/Claw402.png",
    "ClawCredit": "icons/ClawCredit.png",
    "ClawHub": "icons/ClawHub.png",
    "ClawManager": "icons/ClawManager.png",
    "ClawPal": "icons/ClawPal.png",
    "ClawSkills": "icons/ClawSkills.webp",
    "ClawVault": "icons/ClawVault.png",
    "ClawWatcher": "icons/ClawWatcher.png",
    "Clawcard.sh": "icons/Clawcardsh.png",
    "Clawvard": "icons/Clawvard.png",
    "Cleanup.pictures": "icons/Cleanuppictures.png",
    "Click2Magic": "icons/Click2Magic.png",
    "ClientZen": "icons/ClientZen.png",
    "Cline": "icons/Cline.png",
    "ClipDrop Image Upscaler": "icons/ClipDrop_Image_Upscaler.png",
    "ClipDrop Remove Background": "icons/ClipDrop_Remove_Background.png",
    "ClipMove": "icons/ClipMove.png",
    "Clipchamp AI旁白生成器": "icons/Clipchamp_AI旁白生成器.png",
    "Clipfly": "icons/Clipfly.png",
    "Cliplama": "icons/Cliplama.png",
    "ClippingMagic": "icons/ClippingMagic.png",
    "Closers Copy": "icons/Closers_Copy.png",
    "CoPaw": "icons/CoPaw.svg",
    "CoachPoints AI": "icons/CoachPoints_AI.png",
    "CocoLoop": "icons/CocoLoop.png",
    "Coda AI": "icons/Coda_AI.png",
    "Coddy – Code Makes Perfect": "icons/Coddy_Code_Makes_Perfect.png",
    "Code Coach": "icons/Code_Coach.png",
    "Code Conductor": "icons/Code_Conductor.png",
    "CodeArts Snap": "icons/CodeArts_Snap.png",
    "CodeBuddy": "icons/CodeBuddy.webp",
    "CodeDesign.ai": "icons/CodeDesignai.png",
    "CodeGeeX": "icons/CodeGeeX.png",
    "CodeRabbit": "icons/CodeRabbit.png",
    "CodeSnippets": "icons/CodeSnippets.png",
    "CodeWhisperer": "icons/CodeWhisperer.png",
    "Codeium": "icons/Codeium.webp",
    "Codejet": "icons/Codejet.png",
    "Codeless ONE": "icons/Codeless_ONE.png",
    "Codex": "icons/Codex.png",
    "Codex Atlas": "icons/Codex_Atlas.png",
    "Codex CLI": "icons/Codex_CLI.png",
    "Codiga": "icons/Codiga.png",
    "CodiumAI": "icons/CodiumAI.png",
    "Cody": "icons/Cody.png",
    "Cognexo": "icons/Cognexo.png",
    "Cohere": "icons/Cohere.png",
    "Coinbase": "icons/Coinbase.png",
    "Coinbase AgentKit": "icons/Coinbase_AgentKit.svg",
    "Coleap": "icons/Coleap.png",
    "Collider AI": "icons/Collider_AI.png",
    "Collov AI": "icons/Collov_AI.png",
    "Color Wheel": "icons/Color_Wheel.png",
    "ColorMagic": "icons/ColorMagic.png",
    "ColorifyAI": "icons/ColorifyAI.png",
    "Colorin AI": "icons/Colorin_AI.png",
    "Colors AI": "icons/Colors_AI.png",
    "Colourlab": "icons/Colourlab.png",
    "Colourlab.ai": "icons/Colourlabai.png",
    "Comate": "icons/Comate.png",
    "Comment Fast – AI Comment Generator for Social Media": "icons/Comment_Fast_AI_Comment_Generator_for_Social_Media.png",
    "Comments Analytics": "icons/Comments_Analytics.png",
    "CommentsPro – LinkedIn AI Comments Generator": "icons/CommentsPro_LinkedIn_AI_Comments_Generator.png",
    "Competely": "icons/Competely.png",
    "Competitors App": "icons/Competitors_App.png",
    "ComplyCube": "icons/ComplyCube.png",
    "Composable Prompts": "icons/Composable_Prompts.png",
    "Connected Papers": "icons/Connected_Papers.png",
    "Constellab": "icons/Constellab.png",
    "Contenda": "icons/Contenda.png",
    "Content AI reader": "icons/Content_AI_reader.png",
    "ContentQuiver": "icons/ContentQuiver.png",
    "ContentRadar": "icons/ContentRadar.png",
    "ContentWiz – Your AI assistant for Linkedin": "icons/ContentWiz_Your_AI_assistant_for_Linkedin.png",
    "Contentdrips": "icons/Contentdrips.png",
    "ContextQA": "icons/ContextQA.png",
    "Continual": "icons/Continual.png",
    "Continue": "icons/Continue.png",
    "Control Center": "icons/Control_Center.svg",
    "Conversational Demos": "icons/Conversational_Demos.png",
    "Convictional": "icons/Convictional.png",
    "Cookly": "icons/Cookly.png",
    "Copilot": "icons/Copilot.png",
    "CopyLeaks": "icons/CopyLeaks.png",
    "CopyPilot": "icons/CopyPilot.png",
    "Copyter": "icons/Copyter.png",
    "Copywhiz.ai": "icons/Copywhizai.png",
    "Corvus Link": "icons/Corvus_Link.png",
    "Cosine": "icons/Cosine.png",
    "CosyVoice3": "icons/CosyVoice3.png",
    "Couple Care AI Counselling": "icons/Couple_Care_AI_Counselling.png",
    "Course Hero": "icons/Course_Hero.png",
    "Coursera": "icons/Coursera.png",
    "Cover Letter Writer": "icons/Cover_Letter_Writer.png",
    "CoverLet: Upwork Winning Proposal Generator": "icons/CoverLet_Upwork_Winning_Proposal_Generator.png",
    "CoverPro AI": "icons/CoverPro_AI.png",
    "Coverwraiter": "icons/Coverwraiter.png",
    "Coze": "icons/Coze.png",
    "Craion AI": "icons/Craion_AI.png",
    "Creatie": "icons/Creatie.png",
    "Creatify": "icons/Creatify.png",
    "Creative Blog Topic": "icons/Creative_Blog_Topic.png",
    "Creator tools": "icons/Creator_tools.png",
    "Credit Chip": "icons/Credit_Chip.png",
    "CrewAI": "icons/CrewAI.png",
    "CropandGrade": "icons/CropandGrade.png",
    "CrowdSnap": "icons/CrowdSnap.png",
    "CryptoSkills": "icons/CryptoSkills.webp",
    "CueMe": "icons/CueMe.png",
    "Cuetap": "icons/Cuetap.png",
    "Cursor": "icons/Cursor.png",
    "Cutout.Pro Retouch": "icons/CutoutPro_Retouch.png",
    "Cutout.Pro抠图": "icons/CutoutPro抠图.png",
    "Cutout.Pro老照片上色": "icons/CutoutPro老照片上色.png",
    "C知道": "icons/C知道.png",
    "D&AViz lite": "icons/DAViz_lite.png",
    "DECipher": "icons/DECipher.png",
    "DIY Websites AI Website Builder": "icons/DIY_Websites_AI_Website_Builder.png",
    "DL4J": "icons/DL4J.png",
    "Danelfin": "icons/Danelfin.png",
    "Data Science Kit": "icons/Data_Science_Kit.png",
    "Dates.ai": "icons/Datesai.png",
    "Daytona": "icons/Daytona.png",
    "DearHM": "icons/DearHM.png",
    "Debuild": "icons/Debuild.png",
    "DeckBird.ai": "icons/DeckBirdai.png",
    "Deco": "icons/Deco.png",
    "Decohere": "icons/Decohere.png",
    "DecorAI.xyz": "icons/DecorAIxyz.png",
    "DeepFloyd IF": "icons/DeepFloyd_IF.png",
    "DeepL": "icons/DeepL.png",
    "DeepL Write": "icons/DeepL_Write.png",
    "DeepLearning.AI": "icons/DeepLearningAI.png",
    "DeepL翻译": "icons/DeepL翻译.png",
    "DeepSeek": "icons/DeepSeek.png",
    "DeepSpeed": "icons/DeepSpeed.png",
    "DeepSwapper": "icons/DeepSwapper.png",
    "DeepTranslate": "icons/DeepTranslate.png",
    "DeepUnit": "icons/DeepUnit.png",
    "Deepgram": "icons/Deepgram.png",
    "Definity Legend A.I Game Builder": "icons/Definity_Legend_AI_Game_Builder.png",
    "Deleo.io AI image Generator": "icons/Deleoio_AI_image_Generator.png",
    "Delphos | AI Music": "icons/Delphos_AI_Music.png",
    "DenoLyrics": "icons/DenoLyrics.png",
    "Descript": "icons/Descript.png",
    "Design Champ": "icons/Design_Champ.png",
    "DesignGen": "icons/DesignGen.png",
    "DesignSense AI": "icons/DesignSense_AI.png",
    "Designly AI": "icons/Designly_AI.png",
    "Designs.ai": "icons/Designsai.png",
    "DeskDay": "icons/DeskDay.png",
    "DevChat": "icons/DevChat.png",
    "DevDynamics": "icons/DevDynamics.png",
    "Devana.ai": "icons/Devanaai.png",
    "Devin": "icons/Devin.png",
    "Devv": "icons/Devv.png",
    "Dezgo": "icons/Dezgo.png",
    "DialSense": "icons/DialSense.png",
    "Dialoqbase Lite – A SidePanel & Web UI for AI Models": "icons/Dialoqbase_Lite_A_SidePanel_Web_UI_for_AI_Models.png",
    "Dice la cancion": "icons/Dice_la_cancion.png",
    "Dictanote": "icons/Dictanote.png",
    "Dify": "icons/Dify.png",
    "DigArt365": "icons/DigArt365.png",
    "Digest Diff": "icons/Digest_Diff.png",
    "DigitalGenius": "icons/DigitalGenius.png",
    "Discord官方服务器": "icons/Discord官方服务器.png",
    "Discountly": "icons/Discountly.png",
    "Disgraph": "icons/Disgraph.png",
    "Dishi – The Meal Prep Timer": "icons/Dishi_The_Meal_Prep_Timer.png",
    "Distribute | Death To Whitepapers": "icons/Distribute_Death_To_Whitepapers.png",
    "Dittin AI": "icons/Dittin_AI.png",
    "Dittin AI V2": "icons/Dittin_AI_V2.png",
    "DocWhizz": "icons/DocWhizz.png",
    "Dokuso": "icons/Dokuso.png",
    "Domainchamp.com": "icons/Domainchampcom.png",
    "DomoAI": "icons/DomoAI.png",
    "Dora AI": "icons/Dora_AI.png",
    "Dore AI": "icons/Dore_AI.png",
    "Dorik AI": "icons/Dorik_AI.png",
    "Drawing Prompts Generator by Chatgpt": "icons/Drawing_Prompts_Generator_by_Chatgpt.png",
    "Dream Machine": "icons/Dream_Machine.png",
    "Dream Style & Photo AI Sidebar": "icons/Dream_Style_Photo_AI_Sidebar.png",
    "DreamFace": "icons/DreamFace.png",
    "Dreamina": "icons/Dreamina.png",
    "Drop Your AI": "icons/Drop_Your_AI.png",
    "Dropscale": "icons/Dropscale.png",
    "DuClaw": "icons/DuClaw.webp",
    "DuMate": "icons/DuMate.webp",
    "Duix": "icons/Duix.png",
    "Duo Chat": "icons/Duo_Chat.png",
    "Duply.co": "icons/Duplyco.png",
    "Dvina": "icons/Dvina.png",
    "DynamicAds": "icons/DynamicAds.png",
    "E2B": "icons/E2B.png",
    "EOSI Finance": "icons/EOSI_Finance.png",
    "EasyClaw": "icons/EasyClaw.png",
    "EasyEssay": "icons/EasyEssay.png",
    "EasyGift": "icons/EasyGift.png",
    "EasyJobs – Autofill job applications": "icons/EasyJobs_Autofill_job_applications.png",
    "EasyMark": "icons/EasyMark.png",
    "EasyRFP": "icons/EasyRFP.png",
    "Eazy Editor": "icons/Eazy_Editor.png",
    "EbSynth": "icons/EbSynth.png",
    "Echeta": "icons/Echeta.png",
    "Ecomail": "icons/Ecomail.png",
    "Edaly": "icons/Edaly.png",
    "EdgeOne ClawScan": "icons/EdgeOne_ClawScan.webp",
    "EduWiz.AI": "icons/EduWizAI.png",
    "Elements of AI": "icons/Elements_of_AI.png",
    "Elephant.ai": "icons/Elephantai.png",
    "ElevenLabs": "icons/ElevenLabs.png",
    "Elicit": "icons/Elicit.png",
    "EmailGenius—ChatGPT for Gmail": "icons/EmailGeniusChatGPT_for_Gmail.png",
    "EnergeticAI": "icons/EnergeticAI.png",
    "Engraph": "icons/Engraph.png",
    "EnhanceDocs": "icons/EnhanceDocs.png",
    "Ephes": "icons/Ephes.png",
    "Equixly": "icons/Equixly.png",
    "Essay Builder AI": "icons/Essay_Builder_AI.png",
    "Essay Typer": "icons/Essay_Typer.png",
    "EssayAI.ai": "icons/EssayAIai.png",
    "EssayFlow": "icons/EssayFlow.png",
    "EssayWriter": "icons/EssayWriter.png",
    "EssayWriter io": "icons/EssayWriter_io.png",
    "Essayly.ai": "icons/Essaylyai.png",
    "EtherCTO": "icons/EtherCTO.png",
    "Ethertext": "icons/Ethertext.png",
    "Etna": "icons/Etna.png",
    "EtsyCheck": "icons/EtsyCheck.png",
    "Eva Design System": "icons/Eva_Design_System.png",
    "Evebyte Studio": "icons/Evebyte_Studio.png",
    "EverLearns": "icons/EverLearns.png",
    "Evidently AI": "icons/Evidently_AI.png",
    "Exactly.ai": "icons/Exactlyai.png",
    "ExamGenie AI": "icons/ExamGenie_AI.png",
    "Examify AI": "icons/Examify_AI.png",
    "Eyrene": "icons/Eyrene.png",
    "Fable Prism": "icons/Fable_Prism.png",
    "Face Crop Jet": "icons/Face_Crop_Jet.png",
    "FaceFramer.io": "icons/FaceFramerio.png",
    "Facebook Ads Re-edit": "icons/Facebook_Ads_Re-edit.png",
    "Faceopen": "icons/Faceopen.png",
    "Faceswapper": "icons/Faceswapper.png",
    "Facet": "icons/Facet.png",
    "Faircado": "icons/Faircado.png",
    "Faith Forward": "icons/Faith_Forward.png",
    "FakeYou": "icons/FakeYou.png",
    "Fastlane AI": "icons/Fastlane_AI.png",
    "FeedLens": "icons/FeedLens.png",
    "FieldDay": "icons/FieldDay.png",
    "Fig": "icons/Fig.png",
    "FigJam AI": "icons/FigJam_AI.png",
    "Figma AI": "icons/Figma_AI.png",
    "File Organizer 2000": "icons/File_Organizer_2000.png",
    "FileSpeech": "icons/FileSpeech.png",
    "Fileread AI": "icons/Fileread_AI.png",
    "Filmora": "icons/Filmora.png",
    "Filmora AI Music": "icons/Filmora_AI_Music.png",
    "Find Common Ground AI": "icons/Find_Common_Ground_AI.png",
    "Find My Size": "icons/Find_My_Size.png",
    "FireTexts": "icons/FireTexts.png",
    "Fish Speech": "icons/Fish_Speech.png",
    "Fitten Code": "icons/Fitten_Code.png",
    "FlagEval": "icons/FlagEval.png",
    "Flair AI": "icons/Flair_AI.png",
    "FloatingAI": "icons/FloatingAI.png",
    "Flojoy Studio": "icons/Flojoy_Studio.png",
    "Floutwork": "icons/Floutwork.png",
    "Flow Studio": "icons/Flow_Studio.png",
    "FlowGPT": "icons/FlowGPT.png",
    "FlowUs AI": "icons/FlowUs_AI.png",
    "Flowshot": "icons/Flowshot.png",
    "Fluent": "icons/Fluent.png",
    "Flux AI": "icons/Flux_AI.png",
    "Flux Image": "icons/Flux_Image.png",
    "FluxA": "icons/FluxA.png",
    "FocuSee": "icons/FocuSee.png",
    "Folderer": "icons/Folderer.png",
    "FolkTalk": "icons/FolkTalk.png",
    "ForgeFluencer": "icons/ForgeFluencer.png",
    "Fotor AI Image Upscaler": "icons/Fotor_AI_Image_Upscaler.png",
    "FoxyApps": "icons/FoxyApps.png",
    "Framer AI": "icons/Framer_AI.png",
    "Frederick AI": "icons/Frederick_AI.png",
    "Free AI Song Generator": "icons/Free_AI_Song_Generator.png",
    "Free AI Song Generator – AI-Song.AI": "icons/Free_AI_Song_Generator_AI-SongAI.png",
    "Freshframe": "icons/Freshframe.png",
    "Fronty": "icons/Fronty.png",
    "Fryderyk": "icons/Fryderyk.png",
    "FunASR": "icons/FunASR.png",
    "FunBlocks AI": "icons/FunBlocks_AI.png",
    "Fusion AI": "icons/Fusion_AI.png",
    "G3DAI {Jedi}": "icons/G3DAI_Jedi.png",
    "GLM-4.1V-Thinking-Flash": "icons/GLM-41V-Thinking-Flash.png",
    "GLM-ASR-Nano": "icons/GLM-ASR-Nano.png",
    "GPT": "icons/GPT.png",
    "GPT Cover Letter Generator": "icons/GPT_Cover_Letter_Generator.png",
    "GPT CoverLetter": "icons/GPT_CoverLetter.png",
    "GPT Daddy": "icons/GPT_Daddy.png",
    "GPT Detector": "icons/GPT_Detector.png",
    "GPT-SoVITS": "icons/GPT-SoVITS.png",
    "GPTDoneNotification": "icons/GPTDoneNotification.png",
    "GPTGirlfriend": "icons/GPTGirlfriend.png",
    "GPTURER": "icons/GPTURER.png",
    "GPTZero": "icons/GPTZero.png",
    "GPTinf": "icons/GPTinf.png",
    "Galileo AI": "icons/Galileo_AI.png",
    "Gangr DTF gang Sheet Builder": "icons/Gangr_DTF_gang_Sheet_Builder.png",
    "Gate": "icons/Gate.png",
    "Gate Pay for AI": "icons/Gate_Pay_for_AI.png",
    "Gate Skills Hub": "icons/Gate_Skills_Hub.png",
    "GateClaw": "icons/GateClaw.png",
    "Gatekeep": "icons/Gatekeep.png",
    "Gauss Box": "icons/Gauss_Box.png",
    "GearChain": "icons/GearChain.png",
    "Gemini": "icons/Gemini.png",
    "Gemini CLI": "icons/Gemini_CLI.png",
    "Gemma": "icons/Gemma.png",
    "Gemma 4": "icons/Gemma_4.png",
    "Gen-2": "icons/Gen-2.png",
    "GenRPT": "icons/GenRPT.png",
    "Generate JSON": "icons/Generate_JSON.png",
    "GenerateSong AI": "icons/GenerateSong_AI.png",
    "Generative AI for Beginners": "icons/Generative_AI_for_Beginners.png",
    "Generrated": "icons/Generrated.png",
    "Genius AI Hub": "icons/Genius_AI_Hub.png",
    "Genius PT": "icons/Genius_PT.png",
    "GeniusUI": "icons/GeniusUI.png",
    "Get Hired: AI Cover Letters for UpWork Agency": "icons/Get_Hired_AI_Cover_Letters_for_UpWork_Agency.png",
    "GetClaw": "icons/GetClaw.png",
    "GetIdol AI Story & Game Generator": "icons/GetIdol_AI_Story_Game_Generator.png",
    "GetSales.io": "icons/GetSalesio.png",
    "GetSearchablePDF": "icons/GetSearchablePDF.png",
    "Getimg.ai": "icons/Getimgai.png",
    "Getsound": "icons/Getsound.png",
    "Ghostwriter": "icons/Ghostwriter.png",
    "GiantCampaign": "icons/GiantCampaign.png",
    "GiftIdeasAI": "icons/GiftIdeasAI.png",
    "Gifter: Gift Recommendations": "icons/Gifter_Gift_Recommendations.png",
    "Giftl.io": "icons/Giftlio.png",
    "Giftron: Personalized Gift finder": "icons/Giftron_Personalized_Gift_finder.png",
    "Gignite.ai": "icons/Gigniteai.png",
    "Girlfriendly AI": "icons/Girlfriendly_AI.png",
    "GitBrain": "icons/GitBrain.png",
    "GitHub Copilot": "icons/GitHub_Copilot.png",
    "GitHub Sage": "icons/GitHub_Sage.png",
    "Glimsy AI": "icons/Glimsy_AI.png",
    "Glitching": "icons/Glitching.png",
    "Glov": "icons/Glov.png",
    "Gluecharm": "icons/Gluecharm.png",
    "Gmail GPT Assistant": "icons/Gmail_GPT_Assistant.png",
    "Gmail-GPT": "icons/Gmail-GPT.png",
    "GoDiary: Running Tracker": "icons/GoDiary_Running_Tracker.png",
    "GoEnhance": "icons/GoEnhance.png",
    "GoProd": "icons/GoProd.png",
    "GoSearch": "icons/GoSearch.png",
    "GoatStack.AI": "icons/GoatStackAI.png",
    "GodelBots": "icons/GodelBots.png",
    "Golden Chat": "icons/Golden_Chat.png",
    "GoodListen": "icons/GoodListen.png",
    "Goodnotes": "icons/Goodnotes.png",
    "Gooey.AI": "icons/GooeyAI.png",
    "Google AI": "icons/Google_AI.png",
    "Google AI Studio": "icons/Google_AI_Studio.png",
    "Google Dork Generator": "icons/Google_Dork_Generator.png",
    "Google Genie 2": "icons/Google_Genie_2.png",
    "Google Lyria": "icons/Google_Lyria.svg",
    "Google Meetでの翻訳、文字起こし、議事録": "icons/Google_Meetでの翻訳文字起こし議事録.png",
    "Google Vids": "icons/Google_Vids.png",
    "Google翻译": "icons/Google翻译.png",
    "Goover": "icons/Goover.png",
    "Goriderz SAAS p2p ridesharing & delivery": "icons/Goriderz_SAAS_p2p_ridesharing_delivery.png",
    "GradeGap": "icons/GradeGap.png",
    "GradeLab": "icons/GradeLab.png",
    "Gradio": "icons/Gradio.png",
    "Grammarly": "icons/Grammarly.png",
    "Graphite Note": "icons/Graphite_Note.png",
    "Gravitate": "icons/Gravitate.png",
    "Great Headlines": "icons/Great_Headlines.png",
    "Grok": "icons/Grok.png",
    "Grow My BnB": "icons/Grow_My_BnB.png",
    "Growsy": "icons/Growsy.png",
    "Gumloop": "icons/Gumloop.png",
    "Gymbuddy.ai": "icons/Gymbuddyai.png",
    "H2O EvalGPT": "icons/H2O_EvalGPT.png",
    "HELM": "icons/HELM.png",
    "HTTPie AI": "icons/HTTPie_AI.png",
    "HTX": "icons/HTX.png",
    "HTX AI Skills": "icons/HTX_AI_Skills.png",
    "Habitomic": "icons/Habitomic.png",
    "Haiper": "icons/Haiper.png",
    "Hairviour": "icons/Hairviour.png",
    "Hama": "icons/Hama.png",
    "Handwriting OCR": "icons/Handwriting_OCR.png",
    "Happy Insights": "icons/Happy_Insights.png",
    "Happy Scribe": "icons/Happy_Scribe.png",
    "HappyOyster": "icons/HappyOyster.jpg",
    "Happycapy": "icons/Happycapy.png",
    "Hasty": "icons/Hasty.png",
    "HawkFlow.ai": "icons/HawkFlowai.png",
    "Headshot Generator": "icons/Headshot_Generator.png",
    "HeardThat": "icons/HeardThat.png",
    "Heartfly": "icons/Heartfly.png",
    "Hedra": "icons/Hedra.png",
    "Hello Claw 教程": "icons/Hello_Claw_教程.png",
    "Hello Hiring Manager": "icons/Hello_Hiring_Manager.png",
    "HelpBar.ai": "icons/HelpBarai.png",
    "HelpLook": "icons/HelpLook.png",
    "Hermes Agent": "icons/Hermes_Agent.png",
    "HeyCLI": "icons/HeyCLI.png",
    "HeyFriday": "icons/HeyFriday.png",
    "HeyGen": "icons/HeyGen.png",
    "HeyHaddock": "icons/HeyHaddock.png",
    "HiClaw": "icons/HiClaw.png",
    "HireLakeAI": "icons/HireLakeAI.png",
    "Hireguide": "icons/Hireguide.png",
    "HitPaw Voice Changer": "icons/HitPaw_Voice_Changer.png",
    "HitPaw Watermark Remover": "icons/HitPaw_Watermark_Remover.png",
    "Hocoos": "icons/Hocoos.png",
    "HogwartsAI": "icons/HogwartsAI.png",
    "Homiis": "icons/Homiis.png",
    "HookAds AI": "icons/HookAds_AI.png",
    "HoppyCopy": "icons/HoppyCopy.png",
    "Hotpot AI Background Remover": "icons/Hotpot_AI_Background_Remover.png",
    "Hotpot.ai": "icons/Hotpotai.png",
    "Hotshot": "icons/Hotshot.png",
    "Hubble.cx": "icons/Hubblecx.png",
    "Huemint": "icons/Huemint.png",
    "HuggingFace": "icons/HuggingFace.png",
    "Human Model based AI Images": "icons/Human_Model_based_AI_Images.png",
    "Humanizer.org": "icons/Humanizerorg.png",
    "Humbird AI – Beta": "icons/Humbird_AI_Beta.png",
    "Hustle AI": "icons/Hustle_AI.png",
    "Hustle AI – Cover Letter Generator": "icons/Hustle_AI_Cover_Letter_Generator.png",
    "Hustlix – Make Money with AI": "icons/Hustlix_Make_Money_with_AI.png",
    "Hybrid Poker": "icons/Hybrid_Poker.png",
    "HyperClapper 2.0": "icons/HyperClapper_20.png",
    "HyperWrite AI": "icons/HyperWrite_AI.png",
    "Hyperbrowser": "icons/Hyperbrowser.svg",
    "IBM Watson文字转语音": "icons/IBM_Watson文字转语音.png",
    "INOP": "icons/INOP.png",
    "IOPaint": "icons/IOPaint.png",
    "IQuit.ai": "icons/IQuitai.png",
    "IconGen": "icons/IconGen.png",
    "IconWizardAI": "icons/IconWizardAI.png",
    "IconifyAI": "icons/IconifyAI.png",
    "Icons8 Background Remover": "icons/Icons8_Background_Remover.png",
    "Icons8 Smart Upscaler": "icons/Icons8_Smart_Upscaler.png",
    "IdeasAI": "icons/IdeasAI.png",
    "Illustroke": "icons/Illustroke.png",
    "Ilus AI": "icons/Ilus_AI.png",
    "Image Enlarger": "icons/Image_Enlarger.png",
    "Image GAN": "icons/Image_GAN.png",
    "ImageToPromptAI": "icons/ImageToPromptAI.png",
    "ImageToSEO AI": "icons/ImageToSEO_AI.png",
    "Imagen": "icons/Imagen.png",
    "Img.Upscaler": "icons/ImgUpscaler.png",
    "Imgcook": "icons/Imgcook.png",
    "Imgi.in": "icons/Imgiin.png",
    "Impossible Images": "icons/Impossible_Images.png",
    "InFold": "icons/InFold.png",
    "InShop Fashion": "icons/InShop_Fashion.png",
    "InStreet": "icons/InStreet.png",
    "InVideo AI": "icons/InVideo_AI.png",
    "InboxGPT": "icons/InboxGPT.png",
    "IndexTTS-2": "icons/IndexTTS-2.png",
    "Indicia Labs Platform": "icons/Indicia_Labs_Platform.png",
    "Industrial Render AI": "icons/Industrial_Render_AI.png",
    "Infichat": "icons/Infichat.png",
    "InfluencerFarm": "icons/InfluencerFarm.png",
    "Infografix": "icons/Infografix.png",
    "Ink To Ivy": "icons/Ink_To_Ivy.png",
    "Inkey.ai": "icons/Inkeyai.png",
    "Inktee ai": "icons/Inktee_ai.png",
    "Inkwise AI": "icons/Inkwise_AI.png",
    "Insight Video IA": "icons/Insight_Video_IA.png",
    "InsightBaseAI": "icons/InsightBaseAI.png",
    "InsightFactory": "icons/InsightFactory.png",
    "Insightio AI": "icons/Insightio_AI.png",
    "Instant Programmatic SEO": "icons/Instant_Programmatic_SEO.png",
    "InstantAd": "icons/InstantAd.png",
    "InstantArt.io": "icons/InstantArtio.png",
    "Instantgen AI": "icons/Instantgen_AI.png",
    "IntelliMail": "icons/IntelliMail.png",
    "Intently": "icons/Intently.png",
    "Intics": "icons/Intics.png",
    "Inventory365": "icons/Inventory365.png",
    "Iwand style": "icons/Iwand_style.png",
    "JAX": "icons/JAX.png",
    "JVS Claw": "icons/JVS_Claw.ico",
    "Jackrabbit Ops": "icons/Jackrabbit_Ops.png",
    "JamGPT": "icons/JamGPT.png",
    "Jamboss": "icons/Jamboss.png",
    "Jan": "icons/Jan.png",
    "Jarvis": "icons/Jarvis.png",
    "JeecgBoot": "icons/JeecgBoot.ico",
    "Jellyfish": "icons/Jellyfish.png",
    "JetBrains AI": "icons/JetBrains_AI.png",
    "JocondeAI": "icons/JocondeAI.png",
    "Jotlify": "icons/Jotlify.png",
    "JoyCode": "icons/JoyCode.ico",
    "Ju.com": "icons/Jucom.png",
    "Jukebox AI": "icons/Jukebox_AI.png",
    "Julius AI – Analyze Google Sheets with ChatGPT": "icons/Julius_AI_Analyze_Google_Sheets_with_ChatGPT.png",
    "Just Rewrite": "icons/Just_Rewrite.png",
    "K8sGPT": "icons/K8sGPT.png",
    "KLOTO": "icons/KLOTO.png",
    "Kacha AI": "icons/Kacha_AI.png",
    "Kaddo": "icons/Kaddo.png",
    "Kaggle": "icons/Kaggle.png",
    "Kapi: Learn To Write Nepali": "icons/Kapi_Learn_To_Write_Nepali.png",
    "Keble | Online Business Co-Pilot": "icons/Keble_Online_Business_Co-Pilot.png",
    "Keras": "icons/Keras.png",
    "KeyWI – AI Content Marketing Assistant": "icons/KeyWI_AI_Content_Marketing_Assistant.png",
    "Keyword Insights": "icons/Keyword_Insights.png",
    "KiloClaw": "icons/KiloClaw.png",
    "Kimi": "icons/Kimi.webp",
    "Kimi Agent Builder": "icons/Kimi_Agent_Builder.webp",
    "Kimi Chat": "icons/Kimi_Chat.png",
    "Kimi Claw": "icons/Kimi_Claw.webp",
    "Kimi Code": "icons/Kimi_Code.ico",
    "KindlePPT": "icons/KindlePPT.png",
    "Kinso AI": "icons/Kinso_AI.png",
    "Kiro": "icons/Kiro.png",
    "Kittl": "icons/Kittl.png",
    "Klipify": "icons/Klipify.png",
    "Klones": "icons/Klones.png",
    "Koah": "icons/Koah.png",
    "Kode AI": "icons/Kode_AI.png",
    "Kodezi ai": "icons/Kodezi_ai.png",
    "Kodie": "icons/Kodie.png",
    "Kognics LMS": "icons/Kognics_LMS.png",
    "Koko AI": "icons/Koko_AI.png",
    "Kolena Restructured": "icons/Kolena_Restructured.png",
    "Korus": "icons/Korus.png",
    "Kraken": "icons/Kraken.png",
    "Krea AI": "icons/Krea_AI.png",
    "KreadoAI": "icons/KreadoAI.png",
    "Krisp": "icons/Krisp.png",
    "Kroto – AI": "icons/Kroto_AI.png",
    "KuCoin": "icons/KuCoin.png",
    "KuCoin Skills Hub": "icons/KuCoin_Skills_Hub.png",
    "Kurt: Sales Copies that Convert": "icons/Kurt_Sales_Copies_that_Convert.png",
    "KvantsAI": "icons/KvantsAI.png",
    "Kwetzal": "icons/Kwetzal.png",
    "Kyber": "icons/Kyber.png",
    "Kyugo": "icons/Kyugo.png",
    "LALAL.AI": "icons/LALALAI.png",
    "LLMEval3": "icons/LLMEval3.png",
    "LLMonitor": "icons/LLMonitor.png",
    "LOVO AI": "icons/LOVO_AI.png",
    "LTX Studio": "icons/LTX_Studio.png",
    "Label Studio": "icons/Label_Studio.png",
    "Lamanote": "icons/Lamanote.png",
    "Lamini": "icons/Lamini.png",
    "Lander": "icons/Lander.png",
    "Landing Pro AI": "icons/Landing_Pro_AI.png",
    "Landing.ai": "icons/Landingai.png",
    "Landrific Ai": "icons/Landrific_Ai.png",
    "LangChain": "icons/LangChain.png",
    "LangFlow": "icons/LangFlow.webp",
    "LangGPT": "icons/LangGPT.png",
    "LangGraph": "icons/LangGraph.png",
    "Languify": "icons/Languify.png",
    "Layer": "icons/Layer.png",
    "Layerup": "icons/Layerup.png",
    "Lazy Teacher": "icons/Lazy_Teacher.png",
    "Le Chat": "icons/Le_Chat.png",
    "Leap": "icons/Leap.png",
    "Learn.xyz": "icons/Learnxyz.png",
    "LearnEase": "icons/LearnEase.png",
    "Learning Prompt": "icons/Learning_Prompt.png",
    "Leet Resume: Expert, AI-Assisted Resumes": "icons/Leet_Resume_Expert_AI-Assisted_Resumes.png",
    "Legaliser": "icons/Legaliser.png",
    "Lemonaid": "icons/Lemonaid.png",
    "Lendal Copy": "icons/Lendal_Copy.png",
    "LensGo": "icons/LensGo.png",
    "Lernmi": "icons/Lernmi.png",
    "LetterGen – AI Cover Letter Generator": "icons/LetterGen_AI_Cover_Letter_Generator.png",
    "LetterGenie – Craft and Download Your Perfect Cover Letter in Seconds.": "icons/LetterGenie_Craft_and_Download_Your_Perfect_Cover_Letter_in_Seconds.png",
    "LetterLabsAI": "icons/LetterLabsAI.png",
    "Letterfy": "icons/Letterfy.png",
    "Lettria": "icons/Lettria.png",
    "Let’s Enhance": "icons/Lets_Enhance.png",
    "Lexica": "icons/Lexica.png",
    "LiarLiar": "icons/LiarLiar.png",
    "Liblib": "icons/Liblib.webp",
    "Libretto.fm": "icons/Librettofm.png",
    "Liffery": "icons/Liffery.png",
    "Lightning AI": "icons/Lightning_AI.png",
    "Lightroom Preset Generator": "icons/Lightroom_Preset_Generator.png",
    "Limbiks – AI Flashcard Generator": "icons/Limbiks_AI_Flashcard_Generator.png",
    "LinguAI": "icons/LinguAI.png",
    "Lingvanex": "icons/Lingvanex.png",
    "Link Letter Pro": "icons/Link_Letter_Pro.png",
    "Linkable": "icons/Linkable.png",
    "Linkers.ai": "icons/Linkersai.png",
    "Linkfox Claw": "icons/Linkfox_Claw.png",
    "Linkrobot AI": "icons/Linkrobot_AI.png",
    "Linkz.ai 2.0": "icons/Linkzai_20.png",
    "LipSurf": "icons/LipSurf.png",
    "Listnr": "icons/Listnr.png",
    "Llama": "icons/Llama.svg",
    "Llama 3": "icons/Llama_3.png",
    "Lobe": "icons/Lobe.png",
    "LobeHub": "icons/LobeHub.png",
    "Lobster.cash": "icons/Lobstercash.png",
    "LobsterAI 有道龙虾": "icons/LobsterAI_有道龙虾.png",
    "LocalPulseIO": "icons/LocalPulseIO.png",
    "Locofy": "icons/Locofy.png",
    "LoginLlama": "icons/LoginLlama.png",
    "Logistify AI": "icons/Logistify_AI.png",
    "Logo Diffusion": "icons/Logo_Diffusion.png",
    "LogoAI": "icons/LogoAI.png",
    "LogoAI – Image Generator": "icons/LogoAI_Image_Generator.png",
    "LogoliveryAI": "icons/LogoliveryAI.png",
    "Logomaster.ai": "icons/Logomasterai.png",
    "Looka": "icons/Looka.png",
    "LooksMaxx AI – AI powered apps to help you glow up and looksmaxx online": "icons/LooksMaxx_AI_AI_powered_apps_to_help_you_glow_up_and_looksmaxx_online.png",
    "Loomy": "icons/Loomy.png",
    "Looti ai": "icons/Looti_ai.png",
    "Love Letter Generator": "icons/Love_Letter_Generator.png",
    "LoveTunesAI": "icons/LoveTunesAI.png",
    "Low Dream": "icons/Low_Dream.png",
    "LowTech AI": "icons/LowTech_AI.png",
    "Luca面壁露卡": "icons/Luca面壁露卡.png",
    "Luigi’s Box": "icons/Luigis_Box.png",
    "Luma AI": "icons/Luma_AI.png",
    "Lurny": "icons/Lurny.png",
    "LyricStudio": "icons/LyricStudio.png",
    "Lyricist.ai": "icons/Lyricistai.png",
    "Lyrics Into Song AI": "icons/Lyrics_Into_Song_AI.png",
    "Lyrist": "icons/Lyrist.png",
    "M00D Ritual": "icons/M00D_Ritual.png",
    "MChat": "icons/MChat.png",
    "MEJ ERP AI": "icons/MEJ_ERP_AI.png",
    "MEJ Sales AI": "icons/MEJ_Sales_AI.png",
    "MJ Prompt Tool": "icons/MJ_Prompt_Tool.png",
    "ML for Beginners": "icons/ML_for_Beginners.png",
    "MLX": "icons/MLX.png",
    "MMBench": "icons/MMBench.png",
    "MMLU": "icons/MMLU.png",
    "MOKI": "icons/MOKI.png",
    "MOSS": "icons/MOSS.png",
    "MOTIV8": "icons/MOTIV8.png",
    "MVP Studio": "icons/MVP_Studio.png",
    "Macar AI": "icons/Macar_AI.png",
    "MachineLearningMastery": "icons/MachineLearningMastery.png",
    "Machines Cash": "icons/Machines_Cash.png",
    "Magai": "icons/Magai.png",
    "Magic Design": "icons/Magic_Design.png",
    "Magic Eraser": "icons/Magic_Eraser.png",
    "Magic Form": "icons/Magic_Form.png",
    "MagicReply AI": "icons/MagicReply_AI.png",
    "Magicam": "icons/Magicam.png",
    "Magician": "icons/Magician.png",
    "Magician (Figma)": "icons/Magician_Figma.png",
    "Magnific AI": "icons/Magnific_AI.png",
    "MailboxKit": "icons/MailboxKit.png",
    "Maintain-AI – Good Roads Cost Less": "icons/Maintain-AI_Good_Roads_Cost_Less.png",
    "Mairecipe": "icons/Mairecipe.png",
    "Mana | Accelerate Job Applications with AI": "icons/Mana_Accelerate_Job_Applications_with_AI.png",
    "Manaliza Pro": "icons/Manaliza_Pro.png",
    "Manus": "icons/Manus.ico",
    "Marenda": "icons/Marenda.png",
    "Market Research powered by AI Simulation": "icons/Market_Research_powered_by_AI_Simulation.png",
    "Markey.ai": "icons/Markeyai.png",
    "MarsCode": "icons/MarsCode.png",
    "MarsX": "icons/MarsX.png",
    "Master Cold Outreach with AI": "icons/Master_Cold_Outreach_with_AI.png",
    "MasterGo AI": "icons/MasterGo_AI.png",
    "Math Handwriting API": "icons/Math_Handwriting_API.png",
    "Mavenoid Copilot": "icons/Mavenoid_Copilot.png",
    "MaxAI.me": "icons/MaxAIme.png",
    "MaxClaw": "icons/MaxClaw.png",
    "Me.bot": "icons/Mebot.png",
    "MealForMe": "icons/MealForMe.png",
    "MealSnap: AI meal log journal": "icons/MealSnap_AI_meal_log_journal.png",
    "MedGPT – AI Medication Guide": "icons/MedGPT_AI_Medication_Guide.png",
    "MedReport AI": "icons/MedReport_AI.png",
    "Medheed": "icons/Medheed.png",
    "Media.io AI Image Upscaler": "icons/Mediaio_AI_Image_Upscaler.png",
    "Medoo – Smart Coaching Software": "icons/Medoo_Smart_Coaching_Software.png",
    "MeetLess": "icons/MeetLess.png",
    "Mejorar Imagen": "icons/Mejorar_Imagen.png",
    "Melior Contract Intelligence AI": "icons/Melior_Contract_Intelligence_AI.png",
    "Melobytes.com": "icons/Melobytescom.png",
    "Melodisco AI Music Player": "icons/Melodisco_AI_Music_Player.png",
    "MemFlow": "icons/MemFlow.png",
    "Memeface": "icons/Memeface.png",
    "MemoAI": "icons/MemoAI.png",
    "Memorable Ad Maker": "icons/Memorable_Ad_Maker.png",
    "Mems AI Photo Enhancer": "icons/Mems_AI_Photo_Enhancer.png",
    "Mentor.AI": "icons/MentorAI.png",
    "Menukite": "icons/Menukite.png",
    "Mera Monitor": "icons/Mera_Monitor.png",
    "Meshy": "icons/Meshy.png",
    "Meta AI助手": "icons/Meta_AI助手.png",
    "Meta V-JEPA 2": "icons/Meta_V-JEPA_2.png",
    "MetaMask Skill": "icons/MetaMask_Skill.png",
    "MetaVoice": "icons/MetaVoice.png",
    "Metaview": "icons/Metaview.png",
    "Metering.ai": "icons/Meteringai.png",
    "Mexc": "icons/Mexc.webp",
    "MiMo": "icons/MiMo.png",
    "Michael Ai": "icons/Michael_Ai.png",
    "Microbyte": "icons/Microbyte.png",
    "Microsoft Designer": "icons/Microsoft_Designer.png",
    "MidReal": "icons/MidReal.png",
    "MindPeer": "icons/MindPeer.png",
    "Mindelia": "icons/Mindelia.png",
    "MiniMax": "icons/MiniMax.png",
    "MiniMax Agent Builder": "icons/MiniMax_Agent_Builder.webp",
    "MiniMax Token Plan": "icons/MiniMax_Token_Plan.png",
    "MiniMax 语音": "icons/MiniMax_语音.ico",
    "MiniMax 音乐": "icons/MiniMax_音乐.png",
    "MiracleVision奇想智能": "icons/MiracleVision奇想智能.png",
    "Mistral": "icons/Mistral.png",
    "Mitata AI": "icons/Mitata_AI.png",
    "Mockey AI": "icons/Mockey_AI.png",
    "Modal Sandboxes": "icons/Modal_Sandboxes.ico",
    "Model123": "icons/Model123.webp",
    "Moiful": "icons/Moiful.png",
    "Mokker AI": "icons/Mokker_AI.png",
    "Molo9™": "icons/Molo9.png",
    "Moltbook": "icons/Moltbook.png",
    "Monic AI": "icons/Monic_AI.png",
    "Moodplaylist – AI Powered Playlists": "icons/Moodplaylist_AI_Powered_Playlists.png",
    "MoonPay Agents": "icons/MoonPay_Agents.png",
    "Mootion": "icons/Mootion.png",
    "MoqMeetings": "icons/MoqMeetings.png",
    "Morph Studio": "icons/Morph_Studio.png",
    "Morphic by House of Zoox": "icons/Morphic_by_House_of_Zoox.png",
    "Motiff": "icons/Motiff.png",
    "Motionscribe": "icons/Motionscribe.png",
    "Mubert": "icons/Mubert.svg",
    "MuleRun": "icons/MuleRun.png",
    "Mureka": "icons/Mureka.png",
    "Murf AI": "icons/Murf_AI.png",
    "Museland": "icons/Museland.png",
    "MusicAI: Top AI Music Generator": "icons/MusicAI_Top_AI_Music_Generator.png",
    "MusicStar.AI": "icons/MusicStarAI.png",
    "Mutable": "icons/Mutable.png",
    "Mutable AI": "icons/Mutable_AI.png",
    "My tools.ai": "icons/My_toolsai.png",
    "MyCleverAI": "icons/MyCleverAI.png",
    "MyEssayWriterAI": "icons/MyEssayWriterAI.png",
    "MyPerfectWords": "icons/MyPerfectWords.png",
    "MyReport": "icons/MyReport.png",
    "Myessaytyper.ai": "icons/Myessaytyperai.png",
    "MyiQ.Ai": "icons/MyiQAi.png",
    "Myko AI": "icons/Myko_AI.png",
    "NLTK": "icons/NLTK.png",
    "NOA": "icons/NOA.png",
    "Nack AI": "icons/Nack_AI.png",
    "Namefinder.ai": "icons/Namefinderai.png",
    "Namingram": "icons/Namingram.png",
    "Nando.ai | Generate High-Converting Copy Instantly": "icons/Nandoai_Generate_High-Converting_Copy_Instantly.png",
    "Nanonets": "icons/Nanonets.png",
    "NativeBI": "icons/NativeBI.png",
    "NaturalReader": "icons/NaturalReader.png",
    "NawaCares: AI Therapy & Journal": "icons/NawaCares_AI_Therapy_Journal.png",
    "Neexa AI": "icons/Neexa_AI.png",
    "NemoClaw": "icons/NemoClaw.webp",
    "NeonLingo": "icons/NeonLingo.png",
    "Nero Image Upscaler": "icons/Nero_Image_Upscaler.png",
    "Netcapz": "icons/Netcapz.png",
    "Netus AI": "icons/Netus_AI.png",
    "Neuralarts": "icons/Neuralarts.png",
    "Neuron Make AI": "icons/Neuron_Make_AI.png",
    "Neurture": "icons/Neurture.png",
    "Neverscene": "icons/Neverscene.png",
    "New release: AI Document Intelligence": "icons/New_release_AI_Document_Intelligence.png",
    "NewFuku": "icons/NewFuku.png",
    "NewsParrot": "icons/NewsParrot.png",
    "Nextminds": "icons/Nextminds.png",
    "Nexus AI": "icons/Nexus_AI.png",
    "NightBloom": "icons/NightBloom.png",
    "NoCodeCMS": "icons/NoCodeCMS.png",
    "NoPlagio": "icons/NoPlagio.png",
    "Noisee AI": "icons/Noisee_AI.png",
    "Nolej": "icons/Nolej.png",
    "Notelier AI": "icons/Notelier_AI.png",
    "NotionVC.com": "icons/NotionVCcom.png",
    "Notta": "icons/Notta.png",
    "NovaTalks": "icons/NovaTalks.png",
    "Nudify by FunFun.ai": "icons/Nudify_by_FunFunai.png",
    "NumPy": "icons/NumPy.png",
    "Nurovant AI": "icons/Nurovant_AI.png",
    "ODDY: UX Copilot": "icons/ODDY_UX_Copilot.png",
    "ODESIS": "icons/ODESIS.png",
    "OKX": "icons/OKX.png",
    "OKX Agent Trade Kit": "icons/OKX_Agent_Trade_Kit.png",
    "OLOCR": "icons/OLOCR.png",
    "Oasis AI Minecraft": "icons/Oasis_AI_Minecraft.png",
    "Octavia AI": "icons/Octavia_AI.png",
    "Octocom": "icons/Octocom.png",
    "Odyssei": "icons/Odyssei.png",
    "Off/Script": "icons/OffScript.png",
    "Offorte": "icons/Offorte.png",
    "Ofhepler": "icons/Ofhepler.png",
    "Ohai": "icons/Ohai.png",
    "Oii": "icons/Oii.png",
    "Ollama": "icons/Ollama.png",
    "Olli.ai": "icons/Olliai.png",
    "Olm": "icons/Olm.png",
    "Olovka: AI Essay Writer": "icons/Olovka_AI_Essay_Writer.png",
    "OneStory": "icons/OneStory.png",
    "Onvo AI": "icons/Onvo_AI.png",
    "Open Apps": "icons/Open_Apps.png",
    "Open LLM Leaderboard": "icons/Open_LLM_Leaderboard.png",
    "OpenAISora.video": "icons/OpenAISoravideo.png",
    "OpenClaw": "icons/OpenClaw.png",
    "OpenClaw Directory": "icons/OpenClaw_Directory.png",
    "OpenClaw Startups": "icons/OpenClaw_Startups.png",
    "OpenClaw 中文学习手册": "icons/OpenClaw_中文学习手册.png",
    "OpenClaw 从入门到精通": "icons/OpenClaw_从入门到精通.png",
    "OpenClaw 使用案例": "icons/OpenClaw_使用案例.webp",
    "OpenClaw 官网": "icons/OpenClaw_官网.png",
    "OpenClaw 橙皮书": "icons/OpenClaw_橙皮书.png",
    "OpenClawDir": "icons/OpenClawDir.svg",
    "OpenCompass": "icons/OpenCompass.png",
    "OpenRead": "icons/OpenRead.png",
    "OpenRepli": "icons/OpenRepli.png",
    "OpenRouter": "icons/OpenRouter.ico",
    "OpenRouter Rankings": "icons/OpenRouter_Rankings.png",
    "OpenVoice": "icons/OpenVoice.png",
    "Opnbook": "icons/Opnbook.png",
    "Optigenius.ai": "icons/Optigeniusai.png",
    "OptimizerAI": "icons/OptimizerAI.png",
    "OptionsPro": "icons/OptionsPro.png",
    "Opus Clip": "icons/Opus_Clip.png",
    "Orai": "icons/Orai.png",
    "Orba": "icons/Orba.png",
    "Organelle": "icons/Organelle.png",
    "Originality.AI": "icons/OriginalityAI.png",
    "Osito.ai": "icons/Ositoai.png",
    "OtterTune": "icons/OtterTune.png",
    "Otto AI": "icons/Otto_AI.png",
    "OutSkill Ai": "icons/OutSkill_Ai.png",
    "Outline Ninja": "icons/Outline_Ninja.png",
    "Overwatch Data": "icons/Overwatch_Data.png",
    "OwlOutreach": "icons/OwlOutreach.png",
    "PDF Pilot": "icons/PDF_Pilot.png",
    "PMToolsAI": "icons/PMToolsAI.png",
    "POKY": "icons/POKY.png",
    "PPSPY – Dropshipping by AI": "icons/PPSPY_Dropshipping_by_AI.png",
    "PRODUCTCORE": "icons/PRODUCTCORE.png",
    "PRST.ai": "icons/PRSTai.png",
    "PS2 Filter AI": "icons/PS2_Filter_AI.png",
    "PaLM 2": "icons/PaLM_2.png",
    "Package Design": "icons/Package_Design.png",
    "PaddleSpeech": "icons/PaddleSpeech.png",
    "PageGenie": "icons/PageGenie.png",
    "PageWise AI": "icons/PageWise_AI.png",
    "Pagic": "icons/Pagic.png",
    "Paknevis: AI-based Persian writing assistant": "icons/Paknevis_AI-based_Persian_writing_assistant.png",
    "Palette": "icons/Palette.png",
    "Palm": "icons/Palm.png",
    "Paper Pilot": "icons/Paper_Pilot.png",
    "PaperPilot": "icons/PaperPilot.png",
    "Paperade": "icons/Paperade.png",
    "Paperpal": "icons/Paperpal.png",
    "Papper: Scan Handwritten Todos": "icons/Papper_Scan_Handwritten_Todos.png",
    "Parabrain": "icons/Parabrain.png",
    "Paraphrase Tool & Rewrite App": "icons/Paraphrase_Tool_Rewrite_App.png",
    "Paraphraser": "icons/Paraphraser.png",
    "Paraphrasingtool.ai": "icons/Paraphrasingtoolai.png",
    "Parseflow.io": "icons/Parseflowio.png",
    "Parthean AI": "icons/Parthean_AI.png",
    "Partykit": "icons/Partykit.png",
    "PayAI": "icons/PayAI.png",
    "Pebblely": "icons/Pebblely.png",
    "Pen2txt": "icons/Pen2txt.png",
    "Pentra": "icons/Pentra.png",
    "Pepper Content": "icons/Pepper_Content.png",
    "PerfectEssayWriterAI": "icons/PerfectEssayWriterAI.png",
    "Personadeck.io": "icons/Personadeckio.png",
    "Petals – AI Wear": "icons/Petals_AI_Wear.png",
    "Pgrammer": "icons/Pgrammer.png",
    "Phot.ai": "icons/Photai.png",
    "Photes.io": "icons/Photesio.png",
    "PhotoAid Image Upscaler": "icons/PhotoAid_Image_Upscaler.png",
    "PhotoEcom": "icons/PhotoEcom.png",
    "PhotoMagic": "icons/PhotoMagic.png",
    "PhotoRoom": "icons/PhotoRoom.png",
    "PhotoStudio AI": "icons/PhotoStudio_AI.png",
    "Photoshift": "icons/Photoshift.png",
    "Photune": "icons/Photune.png",
    "Pic Copilot AI抠图": "icons/Pic_Copilot_AI抠图.png",
    "Pic to Text": "icons/Pic_to_Text.png",
    "PicMa Studio": "icons/PicMa_Studio.png",
    "PicTech AI": "icons/PicTech_AI.png",
    "PicWish": "icons/PicWish.png",
    "Picmojo": "icons/Picmojo.png",
    "Pictographic": "icons/Pictographic.png",
    "Picture To Text": "icons/Picture_To_Text.png",
    "PicverseAI": "icons/PicverseAI.png",
    "Pieces for Developers": "icons/Pieces_for_Developers.png",
    "Pika": "icons/Pika.png",
    "Pimento": "icons/Pimento.png",
    "Pincel app": "icons/Pincel_app.png",
    "PinchBench": "icons/PinchBench.png",
    "Pinecone": "icons/Pinecone.png",
    "Ping Path": "icons/Ping_Path.png",
    "Pipeline AI": "icons/Pipeline_AI.png",
    "Pixalto": "icons/Pixalto.png",
    "Pixcleaner remove background": "icons/Pixcleaner_remove_background.png",
    "PixelVibe by Rosebud AI": "icons/PixelVibe_by_Rosebud_AI.png",
    "Pixelcut.ai": "icons/Pixelcutai.png",
    "Pixelfy AI": "icons/Pixelfy_AI.png",
    "Pixelhunter": "icons/Pixelhunter.png",
    "Pixfun": "icons/Pixfun.png",
    "Pixian.AI": "icons/PixianAI.png",
    "Pixso AI": "icons/Pixso_AI.png",
    "Plagiarismsearch.com": "icons/Plagiarismsearchcom.png",
    "PlanPost AI – Best AI Content Generator": "icons/PlanPost_AI_Best_AI_Content_Generator.png",
    "PlanPros.ai": "icons/PlanProsai.png",
    "Plandex": "icons/Plandex.png",
    "Planist.ai": "icons/Planistai.png",
    "PlantsGalore AI Plant Assistant": "icons/PlantsGalore_AI_Plant_Assistant.png",
    "Platen.ai": "icons/Platenai.png",
    "Platoria": "icons/Platoria.png",
    "Play.ht": "icons/Playht.png",
    "Playcards AI": "icons/Playcards_AI.png",
    "Playground AI": "icons/Playground_AI.png",
    "PlaylistAI": "icons/PlaylistAI.png",
    "Plerdy": "icons/Plerdy.png",
    "Ploady": "icons/Ploady.png",
    "Plume AI": "icons/Plume_AI.png",
    "Pocket Hansei": "icons/Pocket_Hansei.png",
    "Podcast": "icons/Podcast.png",
    "Poddy.ai": "icons/Poddyai.png",
    "Podhome": "icons/Podhome.png",
    "Poised: AI-Powered Communication Coach": "icons/Poised_AI-Powered_Communication_Coach.png",
    "Polar": "icons/Polar.png",
    "PolitePost": "icons/PolitePost.png",
    "PoloAPI": "icons/PoloAPI.png",
    "Poly": "icons/Poly.png",
    "PolyHub": "icons/PolyHub.png",
    "Polyzoa Crypto Guard": "icons/Polyzoa_Crypto_Guard.png",
    "PoorClaw穷虾": "icons/PoorClaw穷虾.png",
    "Postsmrt": "icons/Postsmrt.png",
    "Postwise": "icons/Postwise.png",
    "Postys": "icons/Postys.png",
    "Potions": "icons/Potions.png",
    "PowerIn – Automate LinkedIn Comments": "icons/PowerIn_Automate_LinkedIn_Comments.png",
    "PowerPen": "icons/PowerPen.png",
    "Practice Times Tables With AI": "icons/Practice_Times_Tables_With_AI.png",
    "Precious": "icons/Precious.png",
    "Predibase": "icons/Predibase.png",
    "PredictEasy: NoCode ML for Google Sheets": "icons/PredictEasy_NoCode_ML_for_Google_Sheets.png",
    "PrepInterview": "icons/PrepInterview.png",
    "Presentations.ai": "icons/Presentationsai.png",
    "Prime Candidate": "icons/Prime_Candidate.png",
    "ProApp: Learn Design the AI Way": "icons/ProApp_Learn_Design_the_AI_Way.png",
    "ProApply.AI": "icons/ProApplyAI.png",
    "ProMast": "icons/ProMast.png",
    "ProWritingAid": "icons/ProWritingAid.png",
    "Processly": "icons/Processly.png",
    "Producer.AI": "icons/ProducerAI.png",
    "Product Roaster": "icons/Product_Roaster.png",
    "ProductListing.AI": "icons/ProductListingAI.png",
    "ProductPic": "icons/ProductPic.png",
    "ProductScope AI": "icons/ProductScope_AI.png",
    "Productlane": "icons/Productlane.png",
    "Project IDX": "icons/Project_IDX.png",
    "ProjectBloom": "icons/ProjectBloom.png",
    "Prompt Overflow": "icons/Prompt_Overflow.png",
    "Prompt Swipes For Midjourney": "icons/Prompt_Swipes_For_Midjourney.png",
    "PromptBase": "icons/PromptBase.png",
    "PromptHero": "icons/PromptHero.png",
    "PromptPerfect": "icons/PromptPerfect.png",
    "PromptVibes": "icons/PromptVibes.png",
    "PromptVine": "icons/PromptVine.png",
    "PromptVisor": "icons/PromptVisor.png",
    "Prompter – AI Art Prompt Optimizer": "icons/Prompter_AI_Art_Prompt_Optimizer.png",
    "Promptie": "icons/Promptie.png",
    "Promptologer": "icons/Promptologer.png",
    "Proofig": "icons/Proofig.png",
    "Proofreading AI": "icons/Proofreading_AI.png",
    "Propellor ai": "icons/Propellor_ai.png",
    "Proust": "icons/Proust.png",
    "PubMedQA": "icons/PubMedQA.png",
    "PublicPrompts": "icons/PublicPrompts.png",
    "PyTorch": "icons/PyTorch.png",
    "QR Code Craft": "icons/QR_Code_Craft.png",
    "QR-Tube": "icons/QR-Tube.png",
    "Qclaw": "icons/Qclaw.png",
    "Qloze": "icons/Qloze.png",
    "Qoder": "icons/Qoder.png",
    "QoderWork": "icons/QoderWork.png",
    "Qosma AI": "icons/Qosma_AI.png",
    "Qreative AI: Artful QR Codes": "icons/Qreative_AI_Artful_QR_Codes.png",
    "Qualli": "icons/Qualli.png",
    "Quartile": "icons/Quartile.png",
    "Quenti": "icons/Quenti.png",
    "Quest AI": "icons/Quest_AI.png",
    "Question Maker AI": "icons/Question_Maker_AI.png",
    "QuickMail AI": "icons/QuickMail_AI.png",
    "QuickRedact": "icons/QuickRedact.png",
    "Quicktools Background Remover": "icons/Quicktools_Background_Remover.png",
    "QuillBot": "icons/QuillBot.png",
    "Quist AI": "icons/Quist_AI.png",
    "QuizWhiz": "icons/QuizWhiz.png",
    "Quopilot": "icons/Quopilot.png",
    "Qwen-Omni": "icons/Qwen-Omni.png",
    "Qwen3-ASR": "icons/Qwen3-ASR.png",
    "Qwen3-TTS": "icons/Qwen3-TTS.png",
    "RIZILA – Make your life a bit easier.": "icons/RIZILA_Make_your_life_a_bit_easier.png",
    "RTGLabs": "icons/RTGLabs.png",
    "Radical Human Intelligence™": "icons/Radical_Human_Intelligence.png",
    "Raily": "icons/Raily.png",
    "Rainforest": "icons/Rainforest.png",
    "RankU – YouTube Creator Tool": "icons/RankU_YouTube_Creator_Tool.png",
    "RapidClaims.ai": "icons/RapidClaimsai.png",
    "Rash Detector": "icons/Rash_Detector.png",
    "Rask": "icons/Rask.png",
    "Raster": "icons/Raster.png",
    "ReRoom": "icons/ReRoom.png",
    "Reach Best": "icons/Reach_Best.png",
    "ReadPaper Importer": "icons/ReadPaper_Importer.png",
    "Reading Coach": "icons/Reading_Coach.png",
    "Ready Recipes": "icons/Ready_Recipes.png",
    "Realibox AI": "icons/Realibox_AI.png",
    "Receipt Cat": "icons/Receipt_Cat.png",
    "Receipt-AI for Startup": "icons/Receipt-AI_for_Startup.png",
    "RecetasIA": "icons/RecetasIA.png",
    "Recipeasy": "icons/Recipeasy.png",
    "ReconnectEx.com": "icons/ReconnectExcom.png",
    "Recordme": "icons/Recordme.png",
    "Recraft AI": "icons/Recraft_AI.png",
    "RedCom.ai": "icons/RedComai.png",
    "Reddit板块": "icons/Reddit板块.png",
    "Reecho睿声": "icons/Reecho睿声.png",
    "Reeltail: Shop Straight from YouTube Videos.": "icons/Reeltail_Shop_Straight_from_YouTube_Videos.png",
    "Reetail": "icons/Reetail.png",
    "Reica": "icons/Reica.png",
    "Reinforz": "icons/Reinforz.png",
    "Relaied": "icons/Relaied.png",
    "Relight": "icons/Relight.png",
    "Rely.io": "icons/Relyio.png",
    "Remini": "icons/Remini.png",
    "Removal.AI": "icons/RemovalAI.png",
    "Renderfire": "icons/Renderfire.png",
    "Renovy": "icons/Renovy.png",
    "Rep AI: Sales Concierge for eCommerce": "icons/Rep_AI_Sales_Concierge_for_eCommerce.png",
    "Rephrasee – Powered by AI": "icons/Rephrasee_Powered_by_AI.png",
    "Rephrasely": "icons/Rephrasely.png",
    "Rephrasy": "icons/Rephrasy.png",
    "Replicate": "icons/Replicate.png",
    "ReplyMind": "icons/ReplyMind.png",
    "ReplyPulse.com": "icons/ReplyPulsecom.png",
    "Report Generator": "icons/Report_Generator.png",
    "ReportGPT": "icons/ReportGPT.png",
    "ReportPDF": "icons/ReportPDF.png",
    "Reppls": "icons/Reppls.png",
    "Repromptify": "icons/Repromptify.png",
    "Repurposly.ai": "icons/Repurposlyai.png",
    "ResearchPal": "icons/ResearchPal.png",
    "Resemble.ai": "icons/Resembleai.png",
    "Retinello": "icons/Retinello.png",
    "RevAI": "icons/RevAI.png",
    "RevoChat": "icons/RevoChat.png",
    "Rewording Tool": "icons/Rewording_Tool.png",
    "Rewritify: Undetectable AI Rewriter": "icons/Rewritify_Undetectable_AI_Rewriter.png",
    "Riffusion": "icons/Riffusion.png",
    "RikiGPT": "icons/RikiGPT.png",
    "Roach": "icons/Roach.png",
    "Rocket Scooter": "icons/Rocket_Scooter.png",
    "RocketAI": "icons/RocketAI.png",
    "RoleGuides Game Master Assistant Tool": "icons/RoleGuides_Game_Master_Assistant_Tool.png",
    "Room AI": "icons/Room_AI.png",
    "RosyWhale": "icons/RosyWhale.png",
    "Rove": "icons/Rove.png",
    "Rowsup": "icons/Rowsup.png",
    "Ruminare": "icons/Ruminare.png",
    "Runway": "icons/Runway.png",
    "Runway GWM-1": "icons/Runway_GWM-1.png",
    "Runwayml": "icons/Runwayml.png",
    "Rupert AI": "icons/Rupert_AI.png",
    "SDR-GPT": "icons/SDR-GPT.png",
    "SEO AI Bot": "icons/SEO_AI_Bot.png",
    "SEOs.ai": "icons/SEOsai.png",
    "SERP Sonar": "icons/SERP_Sonar.png",
    "SIFA Reply": "icons/SIFA_Reply.png",
    "SLAIT School": "icons/SLAIT_School.png",
    "SaaSlidator": "icons/SaaSlidator.png",
    "SafeSkill": "icons/SafeSkill.ico",
    "Salesforce Einstein 1 Platform for Application Development": "icons/Salesforce_Einstein_1_Platform_for_Application_Development.png",
    "Samwell.Ai": "icons/SamwellAi.png",
    "Sandra AI": "icons/Sandra_AI.png",
    "Saner.ai (Beta version)": "icons/Sanerai_Beta_version.png",
    "Sapling AI Content Detector": "icons/Sapling_AI_Content_Detector.png",
    "Savey Meal-Bot": "icons/Savey_Meal-Bot.png",
    "Savor Smart": "icons/Savor_Smart.png",
    "Saylo": "icons/Saylo.png",
    "Scale AI": "icons/Scale_AI.png",
    "Scalez": "icons/Scalez.png",
    "ScholarCopilot": "icons/ScholarCopilot.png",
    "SciSummary": "icons/SciSummary.png",
    "ScienHub": "icons/ScienHub.png",
    "Scikit-learn": "icons/Scikit-learn.png",
    "Scrape Comfort": "icons/Scrape_Comfort.png",
    "Seamless Studio (Beta)": "icons/Seamless_Studio_Beta.png",
    "SearchOptimizer": "icons/SearchOptimizer.png",
    "SearchUnify": "icons/SearchUnify.png",
    "Secto": "icons/Secto.png",
    "SeeHear – Text Capture": "icons/SeeHear_Text_Capture.png",
    "Seeduplex": "icons/Seeduplex.png",
    "Seeing Dogs": "icons/Seeing_Dogs.png",
    "Segment Anything（SAM）": "icons/Segment_AnythingSAM.png",
    "Selfarama Books": "icons/Selfarama_Books.png",
    "Sell The Trend": "icons/Sell_The_Trend.png",
    "SellerSprite – Amazon Research Tool": "icons/SellerSprite_Amazon_Research_Tool.png",
    "Sellstat – ваш помощник в аналитике": "icons/Sellstat_ваш_помощник_в_аналитике.png",
    "SeniorDev": "icons/SeniorDev.png",
    "Sensi Bot": "icons/Sensi_Bot.png",
    "Shaped": "icons/Shaped.png",
    "ShareID": "icons/ShareID.png",
    "Sherpa-ONNX": "icons/Sherpa-ONNX.png",
    "ShopeeGPT – Optimize Titles & Descriptions": "icons/ShopeeGPT_Optimize_Titles_Descriptions.png",
    "Shortwave AI – Instant summaries, AI writing, AI search for Gmail": "icons/Shortwave_AI_Instant_summaries_AI_writing_AI_search_for_Gmail.png",
    "ShotRate.com": "icons/ShotRatecom.png",
    "ShowMeAI知识社区": "icons/ShowMeAI知识社区.png",
    "Shown": "icons/Shown.png",
    "Showrunner": "icons/Showrunner.png",
    "Shulex Copilot": "icons/Shulex_Copilot.png",
    "Shulex VOC": "icons/Shulex_VOC.png",
    "Shutterstock": "icons/Shutterstock.png",
    "Sigma AI": "icons/Sigma_AI.png",
    "SimFin": "icons/SimFin.png",
    "Simplif.ai": "icons/Simplifai.png",
    "Sintra AI": "icons/Sintra_AI.png",
    "SiteSpeakAI": "icons/SiteSpeakAI.png",
    "Sketch2Code": "icons/Sketch2Code.png",
    "Sketch2scheme": "icons/Sketch2scheme.png",
    "SkillHub": "icons/SkillHub.png",
    "SkillHub中国": "icons/SkillHub中国.png",
    "SkillPay": "icons/SkillPay.webp",
    "Skills.sh": "icons/Skillssh.png",
    "SkillsMP": "icons/SkillsMP.png",
    "Skipped": "icons/Skipped.png",
    "Skoot": "icons/Skoot.png",
    "Skribr": "icons/Skribr.png",
    "SkyAgents": "icons/SkyAgents.png",
    "SkyFrom.earth": "icons/SkyFromearth.png",
    "SkyReels": "icons/SkyReels.png",
    "SkyReels-V3": "icons/SkyReels-V3.png",
    "Skybox AI": "icons/Skybox_AI.png",
    "Slay School": "icons/Slay_School.png",
    "Slazzer": "icons/Slazzer.png",
    "Slidebean Founder Platform": "icons/Slidebean_Founder_Platform.png",
    "SlidesPilot": "icons/SlidesPilot.png",
    "Slite": "icons/Slite.png",
    "SmallVill": "icons/SmallVill.png",
    "Smart Chef AI": "icons/Smart_Chef_AI.png",
    "SmartBids.ai": "icons/SmartBidsai.png",
    "SmartTrust.io": "icons/SmartTrustio.png",
    "Smodin": "icons/Smodin.png",
    "Smodin AI Content Detector": "icons/Smodin_AI_Content_Detector.png",
    "Smodin AI Research Paper": "icons/Smodin_AI_Research_Paper.png",
    "Snack Prompt": "icons/Snack_Prompt.png",
    "Snap2Pass": "icons/Snap2Pass.png",
    "SnapEdit": "icons/SnapEdit.png",
    "SnapFusion.AI": "icons/SnapFusionAI.png",
    "SnapMeasureAI": "icons/SnapMeasureAI.png",
    "Snapby AI – Figma Plugin": "icons/Snapby_AI_Figma_Plugin.png",
    "Snapss": "icons/Snapss.png",
    "Snapy.ai": "icons/Snapyai.png",
    "Snon Lyric": "icons/Snon_Lyric.png",
    "Snowpixel App": "icons/Snowpixel_App.png",
    "Snzzle": "icons/Snzzle.png",
    "Soaster – Growth Your Twitter Account": "icons/Soaster_Growth_Your_Twitter_Account.png",
    "Social AI Assistant": "icons/Social_AI_Assistant.png",
    "Social AI Assistant: Grow your Twitter": "icons/Social_AI_Assistant_Grow_your_Twitter.png",
    "Social AI Next": "icons/Social_AI_Next.png",
    "Social360": "icons/Social360.png",
    "SocialBee": "icons/SocialBee.png",
    "Socky.ai – AI Designed Custom Socks": "icons/Sockyai_AI_Designed_Custom_Socks.png",
    "Softr": "icons/Softr.png",
    "SolidGrids": "icons/SolidGrids.png",
    "Solo": "icons/Solo.png",
    "Sonauto": "icons/Sonauto.png",
    "Song Words": "icons/Song_Words.png",
    "SongR": "icons/SongR.png",
    "Songle AI": "icons/Songle_AI.png",
    "SorSor": "icons/SorSor.png",
    "Sora": "icons/Sora.png",
    "Sora Depot": "icons/Sora_Depot.png",
    "Soula Care": "icons/Soula_Care.png",
    "Souls.zip": "icons/Soulszip.png",
    "SoundHound": "icons/SoundHound.png",
    "Soundful": "icons/Soundful.png",
    "Soundraw": "icons/Soundraw.png",
    "Soundview": "icons/Soundview.png",
    "Sourcio": "icons/Sourcio.png",
    "Space of mind": "icons/Space_of_mind.png",
    "Spark Inmo Pro": "icons/Spark_Inmo_Pro.png",
    "Spark-TTS": "icons/Spark-TTS.png",
    "Spawn": "icons/Spawn.png",
    "SpeakFit": "icons/SpeakFit.png",
    "Specgen.ai": "icons/Specgenai.png",
    "SpeechEvalPro API": "icons/SpeechEvalPro_API.png",
    "Speechify": "icons/Speechify.png",
    "Speechki ChatGPT Plugin: anything audio": "icons/Speechki_ChatGPT_Plugin_anything_audio.png",
    "Sphinx Mind": "icons/Sphinx_Mind.png",
    "Spice.ai": "icons/Spiceai.png",
    "Spikes Studio": "icons/Spikes_Studio.png",
    "Spine": "icons/Spine.png",
    "Spinrewriter": "icons/Spinrewriter.png",
    "Spline AI": "icons/Spline_AI.png",
    "Sprout AI": "icons/Sprout_AI.png",
    "Spyper.ai": "icons/Spyperai.png",
    "Stable Audio": "icons/Stable_Audio.png",
    "Stable Chat": "icons/Stable_Chat.png",
    "Stable Diffusion 3 AI Image Generator Free Online": "icons/Stable_Diffusion_3_AI_Image_Generator_Free_Online.png",
    "Stable Diffusion Prompt Book": "icons/Stable_Diffusion_Prompt_Book.png",
    "Stable Video": "icons/Stable_Video.png",
    "StableLM": "icons/StableLM.png",
    "StableVicuna": "icons/StableVicuna.png",
    "Stackie.AI (Notes, Tracker, Memo & More)": "icons/StackieAI_Notes_Tracker_Memo_More.png",
    "Stadio": "icons/Stadio.png",
    "Stamina AI": "icons/Stamina_AI.png",
    "StarWise Extension": "icons/StarWise_Extension.png",
    "Starmony (AI Music Studio)": "icons/Starmony_AI_Music_Studio.png",
    "StaticBlocks": "icons/StaticBlocks.png",
    "Steel": "icons/Steel.png",
    "Step Plan": "icons/Step_Plan.png",
    "StepClaw": "icons/StepClaw.png",
    "Stepseed": "icons/Stepseed.png",
    "StockAI Vietnam": "icons/StockAI_Vietnam.png",
    "Stocked AI": "icons/Stocked_AI.png",
    "Story321 Music AI": "icons/Story321_Music_AI.png",
    "Sttabot Gamma Access": "icons/Sttabot_Gamma_Access.png",
    "Study Buddy": "icons/Study_Buddy.png",
    "StudyCorgi ChatGPT Detector": "icons/StudyCorgi_ChatGPT_Detector.png",
    "Stylar": "icons/Stylar.png",
    "Stylized": "icons/Stylized.png",
    "Stylus – Magic AI Gmail Assistant": "icons/Stylus_Magic_AI_Gmail_Assistant.png",
    "Submagic": "icons/Submagic.png",
    "SubmitSaaS": "icons/SubmitSaaS.png",
    "SubtitleBee": "icons/SubtitleBee.png",
    "Subvention.app": "icons/Subventionapp.png",
    "Such Much AI": "icons/Such_Much_AI.png",
    "Summify – Summarize speech": "icons/Summify_Summarize_speech.png",
    "Summio": "icons/Summio.png",
    "Suno": "icons/Suno.png",
    "Suno AI Music Generator Free Online": "icons/Suno_AI_Music_Generator_Free_Online.png",
    "SunoCC AI": "icons/SunoCC_AI.png",
    "SuperApply": "icons/SuperApply.png",
    "SuperCLUE": "icons/SuperCLUE.png",
    "Superflow: Annotate live websites": "icons/Superflow_Annotate_live_websites.png",
    "Supermaven": "icons/Supermaven.png",
    "Supertone Shift": "icons/Supertone_Shift.png",
    "SuratFit": "icons/SuratFit.png",
    "Surfaceer": "icons/Surfaceer.png",
    "Swantide": "icons/Swantide.png",
    "Sweephy": "icons/Sweephy.png",
    "Swift Reply": "icons/Swift_Reply.png",
    "Swiftbro": "icons/Swiftbro.png",
    "Swimm AI (Beta)": "icons/Swimm_AI_Beta.png",
    "Syft": "icons/Syft.png",
    "Syllaby": "icons/Syllaby.png",
    "Symanto Text Insights": "icons/Symanto_Text_Insights.png",
    "Symbl.ai": "icons/Symblai.png",
    "Synaptiq": "icons/Synaptiq.png",
    "Syncmerce": "icons/Syncmerce.png",
    "Synthesis": "icons/Synthesis.png",
    "THunt – 免费商品数据分析 & 下载工具": "icons/THunt_免费商品数据分析_下载工具.png",
    "TME Studio": "icons/TME_Studio.png",
    "TTSLabs": "icons/TTSLabs.png",
    "TTSMaker": "icons/TTSMaker.png",
    "TabNine": "icons/TabNine.png",
    "Tabbit 浏览器": "icons/Tabbit_浏览器.png",
    "Tabby": "icons/Tabby.png",
    "Tad AI": "icons/Tad_AI.png",
    "TalentScreen AI": "icons/TalentScreen_AI.png",
    "Talki Guru": "icons/Talki_Guru.png",
    "Tammy AI": "icons/Tammy_AI.png",
    "Tangle.io": "icons/Tangleio.png",
    "Tavern of Azoth": "icons/Tavern_of_Azoth.png",
    "Taxly.ai": "icons/Taxlyai.png",
    "Teleporthq": "icons/Teleporthq.png",
    "Templa8": "icons/Templa8.png",
    "Tempo Wallet": "icons/Tempo_Wallet.png",
    "Tended.ai": "icons/Tendedai.png",
    "TensorFlow": "icons/TensorFlow.png",
    "Tettra": "icons/Tettra.png",
    "Text Snap": "icons/Text_Snap.png",
    "TextToFlowchart.com": "icons/TextToFlowchartcom.png",
    "TextToSpeech": "icons/TextToSpeech.png",
    "Textero AI Essay Writer Pro": "icons/Textero_AI_Essay_Writer_Pro.png",
    "Textero.ai Essay Writer": "icons/Texteroai_Essay_Writer.png",
    "The Artificial Stack": "icons/The_Artificial_Stack.png",
    "The Drive AI": "icons/The_Drive_AI.png",
    "The Prompt Index": "icons/The_Prompt_Index.png",
    "The SORA Museum": "icons/The_SORA_Museum.png",
    "The best Suno AI Lyrics Generator": "icons/The_best_Suno_AI_Lyrics_Generator.png",
    "TheB.AI": "icons/TheBAI.png",
    "ThemAIGuys": "icons/ThemAIGuys.png",
    "Three Sigma": "icons/Three_Sigma.png",
    "Thrivebase": "icons/Thrivebase.png",
    "Ticket AI for Discord": "icons/Ticket_AI_for_Discord.png",
    "Tickles.ai Chatbot": "icons/Ticklesai_Chatbot.png",
    "Tidepool by Aquarium": "icons/Tidepool_by_Aquarium.png",
    "TigerBot": "icons/TigerBot.png",
    "Tinq.ai – NLP API": "icons/Tinqai_NLP_API.png",
    "Toby": "icons/Toby.png",
    "Tomaito": "icons/Tomaito.png",
    "TopView.ai": "icons/TopViewai.png",
    "TopWriter": "icons/TopWriter.png",
    "Topline Pro": "icons/Topline_Pro.png",
    "Track Trade": "icons/Track_Trade.png",
    "Trade Foresight": "icons/Trade_Foresight.png",
    "TraderGPT": "icons/TraderGPT.png",
    "Tradvo": "icons/Tradvo.png",
    "Trae": "icons/Trae.png",
    "TranSmart": "icons/TranSmart.png",
    "Trancy": "icons/Trancy.png",
    "Translate-On-The-Fly": "icons/Translate-On-The-Fly.png",
    "Transvribe": "icons/Transvribe.png",
    "Traq ai": "icons/Traq_ai.png",
    "Treato – Your personal transcriber": "icons/Treato_Your_personal_transcriber.png",
    "TribeArc": "icons/TribeArc.png",
    "TripTrio": "icons/TripTrio.png",
    "True ROAS": "icons/True_ROAS.png",
    "TrueGether": "icons/TrueGether.png",
    "TryHairstyle.com": "icons/TryHairstylecom.png",
    "Tryitonai": "icons/Tryitonai.png",
    "Tunee": "icons/Tunee.png",
    "Turbo Paint : Realtime AI Drawing": "icons/Turbo_Paint_Realtime_AI_Drawing.png",
    "TutorEva": "icons/TutorEva.png",
    "TutorUp – AI Homework & Exam Helper": "icons/TutorUp_AI_Homework_Exam_Helper.png",
    "Tweet Fast[投稿人：carlosdomingues,联系：tweetfastcom@gmail.com]": "icons/Tweet_Fast投稿人carlosdomingues联系tweetfastcomgmailcom.png",
    "Twifts": "icons/Twifts.png",
    "TwinMind": "icons/TwinMind.png",
    "Twinny": "icons/Twinny.png",
    "Twitter Operations Bot": "icons/Twitter_Operations_Bot.png",
    "Twixie: Child-Safe AI App": "icons/Twixie_Child-Safe_AI_App.png",
    "Tynal": "icons/Tynal.png",
    "Type Whisperer Ai": "icons/Type_Whisperer_Ai.png",
    "Typecast": "icons/Typecast.png",
    "Typeframes": "icons/Typeframes.png",
    "UI Ants": "icons/UI_Ants.png",
    "UX Eyer": "icons/UX_Eyer.png",
    "Uberduck": "icons/Uberduck.png",
    "Udacity AI学院": "icons/Udacity_AI学院.png",
    "Udio": "icons/Udio.png",
    "Uizard": "icons/Uizard.png",
    "UltraBrainstomer": "icons/UltraBrainstomer.png",
    "Unbound": "icons/Unbound.png",
    "Uncheck AI": "icons/Uncheck_AI.png",
    "UncovAI Extension": "icons/UncovAI_Extension.png",
    "UndercoverDevs": "icons/UndercoverDevs.png",
    "Undetectable.ai": "icons/Undetectableai.png",
    "Unfig": "icons/Unfig.png",
    "Unifyr.ai": "icons/Unifyrai.png",
    "Unschooler.me": "icons/Unschoolerme.png",
    "Unscreen": "icons/Unscreen.png",
    "Unthread": "icons/Unthread.png",
    "UpCat: Upwork Job Alert & ChatGPT Proposals": "icons/UpCat_Upwork_Job_Alert_ChatGPT_Proposals.png",
    "Upscale.media": "icons/Upscalemedia.png",
    "Upscalepics": "icons/Upscalepics.png",
    "Upwex – AI Tools for Upwork": "icons/Upwex_AI_Tools_for_Upwork.png",
    "Upwork ChatGPT": "icons/Upwork_ChatGPT.png",
    "Userdoc": "icons/Userdoc.png",
    "Userview.ai": "icons/Userviewai.png",
    "Utopic.ai": "icons/Utopicai.png",
    "VMagic": "icons/VMagic.png",
    "Vaanee AI Engine": "icons/Vaanee_AI_Engine.png",
    "Valideo": "icons/Valideo.png",
    "Vals AI": "icons/Vals_AI.svg",
    "VanceAI Image Resizer": "icons/VanceAI_Image_Resizer.png",
    "Vary Content": "icons/Vary_Content.png",
    "Varys AI": "icons/Varys_AI.png",
    "Vectorizer.AI": "icons/VectorizerAI.png",
    "Veed AI Voice Generator": "icons/Veed_AI_Voice_Generator.png",
    "Veed Video Background Remover": "icons/Veed_Video_Background_Remover.png",
    "Vellum": "icons/Vellum.png",
    "Vemus未音": "icons/Vemus未音.png",
    "Vercel AI SDK": "icons/Vercel_AI_SDK.png",
    "Verse": "icons/Verse.png",
    "Vespio.ai": "icons/Vespioai.png",
    "Vestium AI": "icons/Vestium_AI.png",
    "ViGen": "icons/ViGen.png",
    "Vibrance": "icons/Vibrance.png",
    "VidAI": "icons/VidAI.png",
    "VidAU AI Video Audio Generator": "icons/VidAU_AI_Video_Audio_Generator.png",
    "Viddyoze": "icons/Viddyoze.png",
    "Videmak Research AI": "icons/Videmak_Research_AI.png",
    "Video Studio": "icons/Video_Studio.png",
    "VideoMuse": "icons/VideoMuse.png",
    "Vidful.ai": "icons/Vidfulai.png",
    "Vidu": "icons/Vidu.png",
    "VietBot AI": "icons/VietBot_AI.png",
    "ViewOn": "icons/ViewOn.png",
    "Viggle": "icons/Viggle.png",
    "Vimi": "icons/Vimi.png",
    "Vinteo": "icons/Vinteo.png",
    "ViralMarketer": "icons/ViralMarketer.png",
    "ViralVideo": "icons/ViralVideo.png",
    "Viralify AI": "icons/Viralify_AI.png",
    "Viralshort": "icons/Viralshort.png",
    "VisCap.ai": "icons/VisCapai.png",
    "Visinova": "icons/Visinova.png",
    "VisionCare": "icons/VisionCare.png",
    "VisionMorpher": "icons/VisionMorpher.png",
    "Visual Prompt Builder": "icons/Visual_Prompt_Builder.png",
    "Visual Studio IntelliCode": "icons/Visual_Studio_IntelliCode.png",
    "Vita: Food Scanner": "icons/Vita_Food_Scanner.png",
    "Viva": "icons/Viva.png",
    "Vizard": "icons/Vizard.png",
    "Vizcom": "icons/Vizcom.png",
    "Vmake AI": "icons/Vmake_AI.png",
    "Vocation": "icons/Vocation.png",
    "Vocs AI": "icons/Vocs_AI.png",
    "Voice.ai": "icons/Voiceai.png",
    "VoiceFox": "icons/VoiceFox.png",
    "Voicemaker": "icons/Voicemaker.png",
    "Voicemod": "icons/Voicemod.png",
    "Voicenotes": "icons/Voicenotes.png",
    "Voicit: Resumen reunión IA y notas online": "icons/Voicit_Resumen_reunión_IA_y_notas_online.png",
    "Vossle": "icons/Vossle.png",
    "Vowel": "icons/Vowel.png",
    "VoxCPM2": "icons/VoxCPM2.png",
    "VoxCraft": "icons/VoxCraft.png",
    "Voxme": "icons/Voxme.png",
    "Voxtral": "icons/Voxtral.png",
    "Vozo": "icons/Vozo.png",
    "Vulse": "icons/Vulse.png",
    "WEAPONIZED RESUME": "icons/WEAPONIZED_RESUME.png",
    "WPS智能写作": "icons/WPS智能写作.png",
    "Walles.ai – Your AI Browser Sidekick": "icons/Wallesai_Your_AI_Browser_Sidekick.png",
    "WalmartGPT:ChatGPT for Walmart Open AI Writer": "icons/WalmartGPTChatGPT_for_Walmart_Open_AI_Writer.png",
    "Wanderboat": "icons/Wanderboat.png",
    "Wanderias": "icons/Wanderias.png",
    "Warp": "icons/Warp.png",
    "WarpSound AI Music API": "icons/WarpSound_AI_Music_API.png",
    "WatermarkRemover": "icons/WatermarkRemover.png",
    "Watermelon Pulse": "icons/Watermelon_Pulse.png",
    "Watsonx.ai": "icons/Watsonxai.png",
    "WaytoAGI 之路": "icons/WaytoAGI_之路.png",
    "We Report Work": "icons/We_Report_Work.png",
    "WeGuru": "icons/WeGuru.png",
    "WeInvest": "icons/WeInvest.png",
    "Webcam Motion Capture": "icons/Webcam_Motion_Capture.png",
    "Weex": "icons/Weex.png",
    "Wegic": "icons/Wegic.png",
    "WellSaid Labs": "icons/WellSaid_Labs.png",
    "Whatsapp Business API": "icons/Whatsapp_Business_API.png",
    "Wheezeless": "icons/Wheezeless.png",
    "Whisper": "icons/Whisper.png",
    "Why the Click": "icons/Why_the_Click.png",
    "Windsurf": "icons/Windsurf.ico",
    "WinkStudio": "icons/WinkStudio.png",
    "Winston AI": "icons/Winston_AI.png",
    "Wisecut": "icons/Wisecut.png",
    "Wishgram": "icons/Wishgram.png",
    "Wizapply: Your AI job-hunting assistant": "icons/Wizapply_Your_AI_job-hunting_assistant.png",
    "WizyChat": "icons/WizyChat.png",
    "Wonder Studio": "icons/Wonder_Studio.png",
    "WonderShare Virbo": "icons/WonderShare_Virbo.png",
    "Wondera": "icons/Wondera.png",
    "Wondercraft": "icons/Wondercraft.png",
    "Wonderin Resume AI": "icons/Wonderin_Resume_AI.png",
    "Word Dose German": "icons/Word_Dose_German.png",
    "Wordjotter": "icons/Wordjotter.png",
    "Wordplus.ai": "icons/Wordplusai.png",
    "Wordvice AI": "icons/Wordvice_AI.png",
    "Worgit.ai": "icons/Worgitai.png",
    "Work Hunty": "icons/Work_Hunty.png",
    "WorkBuddy": "icons/WorkBuddy.svg",
    "WorkViz": "icons/WorkViz.png",
    "WorkbookPDF": "icons/WorkbookPDF.png",
    "WorldLabs Marble": "icons/WorldLabs_Marble.png",
    "Write Label": "icons/Write_Label.png",
    "Write a Card": "icons/Write_a_Card.png",
    "WriteWise": "icons/WriteWise.png",
    "Writecream AI Content Detector": "icons/Writecream_AI_Content_Detector.png",
    "Writefull for Overleaf": "icons/Writefull_for_Overleaf.png",
    "WritingPal": "icons/WritingPal.png",
    "X-Me": "icons/X-Me.png",
    "XO Analytics": "icons/XO_Analytics.png",
    "XPaper AI": "icons/XPaper_AI.png",
    "XSCT Bench": "icons/XSCT_Bench.webp",
    "XT.com": "icons/XTcom.png",
    "Xcrawl": "icons/Xcrawl.png",
    "Xero.AI": "icons/XeroAI.png",
    "Xiaomi MiMo": "icons/Xiaomi_MiMo.png",
    "Xiaomi MiMo Claw": "icons/Xiaomi_MiMo_Claw.png",
    "Xiaomi MiMo-V2-TTS": "icons/Xiaomi_MiMo-V2-TTS.png",
    "YACSS": "icons/YACSS.png",
    "YOMO AI": "icons/YOMO_AI.png",
    "Yignite助手": "icons/Yignite助手.png",
    "YoBulk": "icons/YoBulk.png",
    "YoYo": "icons/YoYo.png",
    "Yoomナレッジ": "icons/Yoomナレッジ.png",
    "YouMusic.AI": "icons/YouMusicAI.png",
    "Your Music Marketing": "icons/Your_Music_Marketing.png",
    "ZAPRO AI": "icons/ZAPRO_AI.png",
    "ZBrain": "icons/ZBrain.png",
    "Zed AI": "icons/Zed_AI.png",
    "ZenMux": "icons/ZenMux.svg",
    "ZenStudio": "icons/ZenStudio.png",
    "Zenfetch": "icons/Zenfetch.png",
    "Zeno – AI Knowledge Assistant": "icons/Zeno_AI_Knowledge_Assistant.png",
    "Zipik": "icons/Zipik.png",
    "ZoZo 2.0": "icons/ZoZo_20.png",
    "Zopia": "icons/Zopia.png",
    "Zyro AI Background Remover": "icons/Zyro_AI_Background_Remover.png",
    "Zyro AI Image Upscaler": "icons/Zyro_AI_Image_Upscaler.png",
    "aiXcoder": "icons/aiXcoder.png",
    "aimusic.one": "icons/aimusicone.png",
    "aipaperwriter.org": "icons/aipaperwriterorg.png",
    "ambit.ai": "icons/ambitai.png",
    "aomni": "icons/aomni.png",
    "audioshake.ai": "icons/audioshakeai.png",
    "automaited": "icons/automaited.png",
    "avavox": "icons/avavox.png",
    "ayraa": "icons/ayraa.png",
    "aysa.ai": "icons/aysaai.png",
    "beeazt": "icons/beeazt.png",
    "blockbank": "icons/blockbank.png",
    "bout.ai — Upgrading team communication": "icons/boutai_Upgrading_team_communication.png",
    "branchbob.ai": "icons/branchbobai.png",
    "calmify.ai": "icons/calmifyai.png",
    "cgfaces.com": "icons/cgfacescom.png",
    "createwebsite.io": "icons/createwebsiteio.png",
    "cretorial AI": "icons/cretorial_AI.png",
    "crovert": "icons/crovert.png",
    "csv2ai": "icons/csv2ai.png",
    "curioustone": "icons/curioustone.png",
    "cvnow.ai": "icons/cvnowai.png",
    "datafarmr": "icons/datafarmr.png",
    "designedbyai io": "icons/designedbyai_io.png",
    "designtools.ai": "icons/designtoolsai.png",
    "draft1.ai": "icons/draft1ai.png",
    "editGPT": "icons/editGPT.png",
    "eduPhoria": "icons/eduPhoria.png",
    "elv.ai": "icons/elvai.png",
    "essayget": "icons/essayget.png",
    "evov.ai": "icons/evovai.png",
    "fast.ai": "icons/fastai.png",
    "flashlab.io": "icons/flashlabio.png",
    "footagentexam.com": "icons/footagentexamcom.png",
    "formNinja": "icons/formNinja.png",
    "formx ai": "icons/formx_ai.png",
    "getactyv": "icons/getactyv.png",
    "hahaOCR": "icons/hahaOCR.png",
    "heardeer": "icons/heardeer.png",
    "iFlyCode": "icons/iFlyCode.png",
    "iFoto": "icons/iFoto.png",
    "iSamurai": "icons/iSamurai.png",
    "illostrationAI": "icons/illostrationAI.png",
    "indexGPTs": "icons/indexGPTs.png",
    "intelligenius.ai": "icons/intelligeniusai.png",
    "intercom.com": "icons/intercomcom.png",
    "inventoro.com": "icons/inventorocom.png",
    "jpgHD": "icons/jpgHD.png",
    "learnmate.app": "icons/learnmateapp.png",
    "looksounique.com": "icons/looksouniquecom.png",
    "luw.ai": "icons/luwai.png",
    "magickimg": "icons/magickimg.png",
    "mails": "icons/mails.png",
    "myEssai": "icons/myEssai.png",
    "n1n.ai": "icons/n1nai.png",
    "neonFin": "icons/neonFin.png",
    "nexpost": "icons/nexpost.png",
    "nexu": "icons/nexu.png",
    "niia.ai": "icons/niiaai.png",
    "only one ai": "icons/only_one_ai.png",
    "papermerge.com": "icons/papermergecom.png",
    "powered by ChatGPT": "icons/powered_by_ChatGPT.png",
    "re:write": "icons/rewrite.png",
    "receitas.ai": "icons/receitasai.png",
    "remove.bg": "icons/removebg.png",
    "restorePhotos.io": "icons/restorePhotosio.png",
    "rhyme.cool": "icons/rhymecool.png",
    "rithmm™": "icons/rithmm.png",
    "rotorvideos.com": "icons/rotorvideoscom.png",
    "samsearch": "icons/samsearch.png",
    "sclof": "icons/sclof.png",
    "sectionschool.com": "icons/sectionschoolcom.png",
    "sellesta.com": "icons/sellestacom.png",
    "sitelifter.com": "icons/siteliftercom.png",
    "smoc.ai": "icons/smocai.png",
    "squirai.com": "icons/squiraicom.png",
    "startuptools.ai": "icons/startuptoolsai.png",
    "stepsize.com": "icons/stepsizecom.png",
    "talktohire": "icons/talktohire.png",
    "teachr": "icons/teachr.png",
    "theSkills.ai": "icons/theSkillsai.png",
    "transkrip.xyz": "icons/transkripxyz.png",
    "transpic": "icons/transpic.png",
    "tribefii Gig Idea Generator": "icons/tribefii_Gig_Idea_Generator.png",
    "tulz.AI": "icons/tulzAI.png",
    "tutorocean.com": "icons/tutoroceancom.png",
    "txyz": "icons/txyz.png",
    "txyz.ai": "icons/txyzai.png",
    "uJam AI: Turn Text to Tunes": "icons/uJam_AI_Turn_Text_to_Tunes.png",
    "unremot": "icons/unremot.png",
    "v0": "icons/v0.png",
    "v0 report": "icons/v0_report.png",
    "v0.dev": "icons/v0dev.png",
    "viable": "icons/viable.png",
    "weelinking": "icons/weelinking.png",
    "wisello": "icons/wisello.png",
    "wondershare.com": "icons/wondersharecom.png",
    "wuko": "icons/wuko.png",
    "x.aihelperkit": "icons/xaihelperkit.png",
    "zero1cine": "icons/zero1cine.png",
    "{descrb}": "icons/descrb.png",
    "一起剪": "icons/一起剪.png",
    "一键抠图": "icons/一键抠图.png",
    "七牛云": "icons/七牛云.ico",
    "万兴喵影": "icons/万兴喵影.png",
    "万兴播爆": "icons/万兴播爆.png",
    "万彩AI": "icons/万彩AI.png",
    "万彩微影": "icons/万彩微影.png",
    "万相营造": "icons/万相营造.png",
    "万能修图": "icons/万能修图.png",
    "万能小in": "icons/万能小in.png",
    "万象 AI 实验室": "icons/万象_AI_实验室.png",
    "中文用例大全": "icons/中文用例大全.png",
    "二当家-剪刀手": "icons/二当家-剪刀手.png",
    "云蝠智能": "icons/云蝠智能.png",
    "京东云": "icons/京东云.png",
    "京东云JoyAgent": "icons/京东云JoyAgent.png",
    "代码小浣熊": "icons/代码小浣熊.png",
    "代码小浣熊Raccoon": "icons/代码小浣熊Raccoon.png",
    "会译": "icons/会译.png",
    "佰分象AI": "icons/佰分象AI.ico",
    "像素蛋糕PixCake": "icons/像素蛋糕PixCake.png",
    "元景大模型MaaS平台": "icons/元景大模型MaaS平台.png",
    "元象XChat": "icons/元象XChat.png",
    "光速写作": "icons/光速写作.png",
    "冒泡鸭": "icons/冒泡鸭.png",
    "写作蛙": "icons/写作蛙.png",
    "创一AI": "icons/创一AI.png",
    "创作王": "icons/创作王.png",
    "创客贴AI画匠": "icons/创客贴AI画匠.png",
    "创客贴设计": "icons/创客贴设计.png",
    "刺鸟配音": "icons/刺鸟配音.png",
    "剧火AI": "icons/剧火AI.png",
    "动手学深度学习": "icons/动手学深度学习.png",
    "包图AI文生图": "icons/包图AI文生图.png",
    "包图网AI素材库": "icons/包图网AI素材库.png",
    "北极象沉浸式AI翻译": "icons/北极象沉浸式AI翻译.png",
    "匠紫": "icons/匠紫.png",
    "千图设计室AI海报": "icons/千图设计室AI海报.png",
    "千问": "icons/千问.png",
    "千问Qwen": "icons/千问Qwen.png",
    "千鹿AI": "icons/千鹿AI.png",
    "华为Agent Arts": "icons/华为Agent_Arts.png",
    "华为云": "icons/华为云.png",
    "即创": "icons/即创.png",
    "即时AI": "icons/即时AI.png",
    "即构数智人": "icons/即构数智人.png",
    "即梦": "icons/即梦.png",
    "即梦AI": "icons/即梦AI.ico",
    "可图 KOLORS": "icons/可图_KOLORS.png",
    "可灵AI": "icons/可灵AI.png",
    "可灵大模型": "icons/可灵大模型.png",
    "听脑AI": "icons/听脑AI.png",
    "咻图AI": "icons/咻图AI.png",
    "商量SenseChat": "icons/商量SenseChat.png",
    "团队快剪": "icons/团队快剪.png",
    "国家超算互联网": "icons/国家超算互联网.png",
    "图可丽": "icons/图可丽.png",
    "图宇宙": "icons/图宇宙.png",
    "在线抠图": "icons/在线抠图.png",
    "场辞": "icons/场辞.png",
    "墨刀AI": "icons/墨刀AI.png",
    "墨狐AI": "icons/墨狐AI.png",
    "大饼AI变声": "icons/大饼AI变声.png",
    "天壤小白": "icons/天壤小白.png",
    "天工SkyMusic": "icons/天工SkyMusic.png",
    "天工巧绘SkyPaint": "icons/天工巧绘SkyPaint.png",
    "天翼云": "icons/天翼云.ico",
    "奇域AI": "icons/奇域AI.png",
    "奇妙元": "icons/奇妙元.png",
    "奇妙文": "icons/奇妙文.png",
    "如果相机": "icons/如果相机.png",
    "官方GitHub": "icons/官方GitHub.png",
    "官方文档": "icons/官方文档.png",
    "宙语Cosmos": "icons/宙语Cosmos.png",
    "实在Agent": "icons/实在Agent.png",
    "对话写作猫": "icons/对话写作猫.png",
    "寻光": "icons/寻光.png",
    "小云雀AI": "icons/小云雀AI.png",
    "小微智能论文": "icons/小微智能论文.png",
    "小悟空": "icons/小悟空.png",
    "小鱼AI写作": "icons/小鱼AI写作.png",
    "小黄蕉": "icons/小黄蕉.png",
    "山海·知音": "icons/山海知音.png",
    "巨日禄": "icons/巨日禄.png",
    "巨日禄AI故事转视频神器": "icons/巨日禄AI故事转视频神器.png",
    "序列猴子": "icons/序列猴子.png",
    "库宝AI工作助手": "icons/库宝AI工作助手.png",
    "应事AI": "icons/应事AI.png",
    "度加创作工具": "icons/度加创作工具.png",
    "开拍": "icons/开拍.png",
    "开搜AI问答搜索": "icons/开搜AI问答搜索.png",
    "录咖": "icons/录咖.png",
    "彩云小梦": "icons/彩云小梦.png",
    "彩云小译": "icons/彩云小译.png",
    "必剪Studio": "icons/必剪Studio.png",
    "必应翻译": "icons/必应翻译.png",
    "快剪辑": "icons/快剪辑.png",
    "快手万擎": "icons/快手万擎.png",
    "快文CopyDone": "icons/快文CopyDone.png",
    "快转字幕": "icons/快转字幕.png",
    "悉语": "icons/悉语.png",
    "悟智写作": "icons/悟智写作.png",
    "悟空": "icons/悟空.webp",
    "悟道": "icons/悟道.png",
    "悠船": "icons/悠船.png",
    "悦音配音": "icons/悦音配音.png",
    "扣子Coze": "icons/扣子Coze.webp",
    "提示工程指南": "icons/提示工程指南.png",
    "搜狗翻译": "icons/搜狗翻译.png",
    "文心一言": "icons/文心一言.png",
    "文心大模型": "icons/文心大模型.png",
    "文心快码": "icons/文心快码.png",
    "文心智能体平台": "icons/文心智能体平台.png",
    "文思助手": "icons/文思助手.png",
    "文涌Effidit": "icons/文涌Effidit.png",
    "文状元": "icons/文状元.png",
    "新华妙笔": "icons/新华妙笔.png",
    "无问芯穹": "icons/无问芯穹.png",
    "无限画": "icons/无限画.png",
    "昇思MindSpore": "icons/昇思MindSpore.png",
    "易可图": "icons/易可图.png",
    "易撰": "icons/易撰.png",
    "星声AI": "icons/星声AI.png",
    "星流": "icons/星流.png",
    "星火内容运营大师": "icons/星火内容运营大师.png",
    "星火绘镜": "icons/星火绘镜.png",
    "星火网文助手": "icons/星火网文助手.png",
    "星链4SAPI": "icons/星链4SAPI.png",
    "晓语台": "icons/晓语台.png",
    "智元 Genie Envisioner": "icons/智元_Genie_Envisioner.png",
    "智搜": "icons/智搜.png",
    "智绘设计": "icons/智绘设计.png",
    "智谱 Coding Plan": "icons/智谱_Coding_Plan.png",
    "智谱GLM": "icons/智谱GLM.png",
    "智谱清流": "icons/智谱清流.png",
    "智谱清言": "icons/智谱清言.png",
    "智谱清言Agent Studio": "icons/智谱清言Agent_Studio.webp",
    "曝光观察板": "icons/曝光观察板.png",
    "曦灵": "icons/曦灵.png",
    "有言": "icons/有言.png",
    "有道写作": "icons/有道写作.png",
    "有道翻译·AI写作": "icons/有道翻译AI写作.png",
    "来画": "icons/来画.png",
    "树熊写作": "icons/树熊写作.png",
    "梅子Ai论文[投稿人：荔枝,联系：17605163234]": "icons/梅子Ai论文投稿人荔枝联系17605163234.png",
    "模袋云AI": "icons/模袋云AI.png",
    "橙篇": "icons/橙篇.png",
    "歌歌AI写歌": "icons/歌歌AI写歌.jpg",
    "比格AI设计": "icons/比格AI设计.png",
    "水产市场": "icons/水产市场.webp",
    "沃丰科技智呼机器人": "icons/沃丰科技智呼机器人.png",
    "沉浸式翻译": "icons/沉浸式翻译.png",
    "海绵音乐": "icons/海绵音乐.png",
    "海螺问问": "icons/海螺问问.png",
    "深言达意": "icons/深言达意.png",
    "潮际好麦": "icons/潮际好麦.png",
    "火宝短剧": "icons/火宝短剧.png",
    "火山写作": "icons/火山写作.png",
    "火山引擎": "icons/火山引擎.png",
    "火山引擎Coding Plan": "icons/火山引擎Coding_Plan.png",
    "火山方舟": "icons/火山方舟.png",
    "火山翻译": "icons/火山翻译.png",
    "火龙果写作": "icons/火龙果写作.png",
    "灵动AI": "icons/灵动AI.png",
    "灵构AI笔记": "icons/灵构AI笔记.png",
    "灵果短剧AI": "icons/灵果短剧AI.png",
    "爱创作": "icons/爱创作.png",
    "爱改写": "icons/爱改写.png",
    "爱设计": "icons/爱设计.png",
    "牛马 AI": "icons/牛马_AI.ico",
    "特斯拉世界模型": "icons/特斯拉世界模型.png",
    "琅琅配音": "icons/琅琅配音.png",
    "瓴羊Agent One": "icons/瓴羊Agent_One.png",
    "瓴羊Quick Service": "icons/瓴羊Quick_Service.png",
    "白日梦": "icons/白日梦.png",
    "百宝箱Tbox": "icons/百宝箱Tbox.png",
    "百小应": "icons/百小应.png",
    "百度AI伙伴": "icons/百度AI伙伴.png",
    "百度AI助手": "icons/百度AI助手.png",
    "百度AI同传助手": "icons/百度AI同传助手.png",
    "百度AI短剧创作": "icons/百度AI短剧创作.png",
    "百度作家平台": "icons/百度作家平台.png",
    "百度千帆": "icons/百度千帆.png",
    "百度千帆Coding Plan": "icons/百度千帆Coding_Plan.png",
    "百度文心": "icons/百度文心.png",
    "百度智能云": "icons/百度智能云.ico",
    "百度智能云一念": "icons/百度智能云一念.png",
    "百度翻译": "icons/百度翻译.png",
    "盼趣AI": "icons/盼趣AI.png",
    "硅基流动": "icons/硅基流动.png",
    "神经网络入门": "icons/神经网络入门.png",
    "秒画": "icons/秒画.png",
    "秘塔写作猫": "icons/秘塔写作猫.png",
    "稿定AI": "icons/稿定AI.png",
    "笔杆论文": "icons/笔杆论文.png",
    "笔灵AI写作": "icons/笔灵AI写作.png",
    "笔灵AI小说": "icons/笔灵AI小说.png",
    "笔魂AI": "icons/笔魂AI.png",
    "笔魂AI绘画": "icons/笔魂AI绘画.png",
    "简单听记": "icons/简单听记.png",
    "简单设计": "icons/简单设计.png",
    "紫东太初": "icons/紫东太初.png",
    "红薯通AI": "icons/红薯通AI.png",
    "绘影字幕": "icons/绘影字幕.png",
    "绘蛙AI文案": "icons/绘蛙AI文案.png",
    "绘蛙AI消除": "icons/绘蛙AI消除.png",
    "绘蛙AI视频": "icons/绘蛙AI视频.png",
    "网易云音乐·X Studio": "icons/网易云音乐X_Studio.png",
    "网易天音": "icons/网易天音.png",
    "网易天音 XStudio": "icons/网易天音_XStudio.png",
    "网易见外": "icons/网易见外.png",
    "美图云修": "icons/美图云修.png",
    "美图无损放大": "icons/美图无损放大.png",
    "美图设计室": "icons/美图设计室.png",
    "美间": "icons/美间.png",
    "美间AI抠图": "icons/美间AI抠图.png",
    "美间AI无损放大": "icons/美间AI无损放大.png",
    "美间AI消除": "icons/美间AI消除.png",
    "羚珑": "icons/羚珑.png",
    "腾讯云": "icons/腾讯云.jpg",
    "腾讯云 Coding Plan": "icons/腾讯云_Coding_Plan.jpg",
    "腾讯云 Token Plan": "icons/腾讯云_Token_Plan.webp",
    "腾讯云AI代码助手": "icons/腾讯云AI代码助手.png",
    "腾讯云TI平台": "icons/腾讯云TI平台.ico",
    "腾讯交互翻译": "icons/腾讯交互翻译.png",
    "腾讯元宝": "icons/腾讯元宝.png",
    "腾讯扣叮": "icons/腾讯扣叮.png",
    "腾讯智影": "icons/腾讯智影.png",
    "腾讯混元": "icons/腾讯混元.png",
    "腾讯混元Agent平台": "icons/腾讯混元Agent平台.ico",
    "腾讯混元大模型": "icons/腾讯混元大模型.png",
    "腾讯翻译君": "icons/腾讯翻译君.png",
    "艺映AI": "icons/艺映AI.png",
    "艾绘": "icons/艾绘.png",
    "范文喵": "icons/范文喵.png",
    "蓝耘元生代": "icons/蓝耘元生代.png",
    "蓝藻AI": "icons/蓝藻AI.png",
    "蔚来世界模型": "icons/蔚来世界模型.png",
    "蘑兔AI": "icons/蘑兔AI.ico",
    "虾聊": "icons/虾聊.png",
    "虾评Skill": "icons/虾评Skill.png",
    "蚂上有创意": "icons/蚂上有创意.png",
    "蚂蚁数科 Agentar": "icons/蚂蚁数科_Agentar.ico",
    "蛙蛙写作": "icons/蛙蛙写作.png",
    "蜜蜂剪辑": "icons/蜜蜂剪辑.png",
    "蝉镜": "icons/蝉镜.png",
    "行者AI美术": "icons/行者AI美术.png",
    "言犀智能体平台": "icons/言犀智能体平台.png",
    "讯飞公文写作助手": "icons/讯飞公文写作助手.png",
    "讯飞写作": "icons/讯飞写作.png",
    "讯飞星火": "icons/讯飞星火.webp",
    "讯飞星火4.0 API": "icons/讯飞星火40_API.png",
    "讯飞星火认知大模型": "icons/讯飞星火认知大模型.png",
    "讯飞智作": "icons/讯飞智作.png",
    "讯飞智检": "icons/讯飞智检.png",
    "讯飞智能翻译": "icons/讯飞智能翻译.png",
    "讯飞虚拟人": "icons/讯飞虚拟人.png",
    "词魂": "icons/词魂.png",
    "谱乐": "icons/谱乐.png",
    "豆包": "icons/豆包.png",
    "豆包Agent Studio": "icons/豆包Agent_Studio.png",
    "豆包Doubao": "icons/豆包Doubao.webp",
    "豆包MarsCode": "icons/豆包MarsCode.png",
    "豆包大模型": "icons/豆包大模型.png",
    "豆绘AI": "icons/豆绘AI.png",
    "象寄翻译": "icons/象寄翻译.png",
    "超级助理": "icons/超级助理.png",
    "迅捷AI写作": "icons/迅捷AI写作.png",
    "逗逗": "icons/逗逗.png",
    "通义千问": "icons/通义千问.png",
    "通义千问Agent Studio": "icons/通义千问Agent_Studio.webp",
    "通义听悟": "icons/通义听悟.png",
    "通义星尘": "icons/通义星尘.png",
    "通义灵码": "icons/通义灵码.png",
    "造梦日记": "icons/造梦日记.png",
    "造梦次元": "icons/造梦次元.png",
    "酷家乐AI": "icons/酷家乐AI.png",
    "金山快译": "icons/金山快译.png",
    "钉钉·个人版": "icons/钉钉个人版.png",
    "铠盒智能": "icons/铠盒智能.png",
    "闪剪": "icons/闪剪.png",
    "问小白": "icons/问小白.png",
    "阶跃星辰": "icons/阶跃星辰.png",
    "阶跃桌面伙伴": "icons/阶跃桌面伙伴.png",
    "阿贝智能": "icons/阿贝智能.png",
    "阿里云": "icons/阿里云.png",
    "阿里云 AgentBay": "icons/阿里云_AgentBay.png",
    "阿里云AI学习路线": "icons/阿里云AI学习路线.png",
    "阿里云Coding Plan": "icons/阿里云Coding_Plan.png",
    "阿里翻译": "icons/阿里翻译.png",
    "集成 ChatGpt, Bard – 无需 OpenAI 账号 – ChatFree": "icons/集成_ChatGpt_Bard_无需_OpenAI_账号_ChatFree.png",
    "非凡产研": "icons/非凡产研.png",
    "音剪": "icons/音剪.png",
    "音潮": "icons/音潮.png",
    "音疯": "icons/音疯.png",
    "音虫": "icons/音虫.png",
    "顽兔抠图": "icons/顽兔抠图.png",
    "飞书Agent Builder": "icons/飞书Agent_Builder.png",
    "飞书OpenClaw": "icons/飞书OpenClaw.png",
    "飞书官方修炼指南": "icons/飞书官方修炼指南.png",
    "飞影数字人": "icons/飞影数字人.png",
    "飞桨AI Studio": "icons/飞桨AI_Studio.png",
    "飞桨PaddlePaddle": "icons/飞桨PaddlePaddle.png",
    "驭码CodeRider": "icons/驭码CodeRider.png",
    "鬼手剪辑GhostCut": "icons/鬼手剪辑GhostCut.png",
    "魔力工作室": "icons/魔力工作室.png",
    "魔搭GPT（ModelScopeGPT）": "icons/魔搭GPTModelScopeGPT.png",
    "魔搭社区": "icons/魔搭社区.ico",
    "魔撰写作": "icons/魔撰写作.png",
    "魔音工坊": "icons/魔音工坊.png",
    "鲜艺AI抠图": "icons/鲜艺AI抠图.png",
    "鹿班": "icons/鹿班.png",
    "麻小玩虾指南": "icons/麻小玩虾指南.png",
    "스토어링크 공식 크롬 익스텐션 확장 프로그램": "icons/스토어링크_공식_크롬_익스텐션_확장_프로그램.png",
};

// 根据网站名称获取图标
function getIconByName(name) {
    // 处理名称中的特殊字符（如零宽空格）
    var cleanName = name.replace(/[\u200B\u200C\u200D\uFEFF]/g, "").trim();
    return iconMap[cleanName] || iconMap[name] || null;
}
